# Preliminary Data Analytic Pipeline 
Provide a coded solution for each area below.  Where appropriate show output and explanations/insights.  Make sure it runs properly.
You will need to install the libraries below if required just

!pip install < lib >
* [pandas](https://pandas.pydata.org/)  
   * [Pandas Tutorials](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html) 
   * [Pandas Example](https://towardsdatascience.com/30-examples-to-master-pandas-f8a2da751fa4)
* [numpy](https://numpy.org/) 
   * [Numpy Examples](https://numpy.org/doc/stable/user/quickstart.html)
* [scikit-learn with Examples](https://scikit-learn.org/stable) 
* [ydata_profiling](https://ydata-profiling.ydata.ai/docs/master/pages/getting_started/overview.html)

In [ ]:
# !pip install pandas 
# !pip install numpy 
# !pip install scikit-learn 
# !pip install ydata-profiling

In [2]:
import pandas as pd
import numpy as np
import sklearn
from ydata_profiling import ProfileReport
from ydata_profiling.utils.cache import cache_file
from pathlib import Path
from copy import deepcopy
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# Allow full view of DataFrames and Series
pd.set_option('display.max_columns', None)  # None or 1000
# pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

## Data Integration
Use the fraud data set introduced earlier in the course

In [4]:
# data integration
df = pd.read_csv('./transactions-1.csv')

In [5]:
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,sex,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,MO,63453,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
1852390,1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,TX,77566,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
1852391,1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,WA,99323,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
1852392,1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,ID,83643,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
1852393,1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,OK,73034,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

## Format and Type
Determine the format of the file and the types of each feature.

**We see that ***Unnamed: 0*** is simply the index, so we can drop this column since Pandas generates an index upon dataframe creation**

In [6]:
## format and type
fpth = Path('./transactions-1.csv')
print('File format is {}'.format(fpth.suffix))
df = df.drop(columns=['Unnamed: 0'])
pd.set_option('display.max_rows', None)  # or 1000
print('\nThe feature types are:\n{}'.format(df.dtypes))
pd.set_option('display.max_rows', 10)  # or 1000

File format is .csv

The feature types are:
trans_date_trans_time     object
cc_num                     int64
merchant                  object
category                  object
amt                      float64
first                     object
last                      object
sex                       object
street                    object
city                      object
state                     object
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                       object
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object

## Analysis
Determine the dynamics of each feature (int/float - math stats, text - categorical or not)

**First we check for any nan entries**

In [7]:
for col in df.columns:
    print('{} {}'.format(df[col].isna().sum(), col))

0 trans_date_trans_time
0 cc_num
0 merchant
0 category
0 amt
0 first
0 last
0 sex
0 street
0 city
0 state
0 zip
0 lat
0 long
0 city_pop
0 job
0 dob
0 trans_num
0 unix_time
0 merch_lat
0 merch_long
0 is_fraud

**Then we check the format/type of *trans_date_trans_time*.**

In [8]:
# analysis
print(type(df['trans_date_trans_time'][0]))
print(df['trans_date_trans_time'][0])
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

<class 'str'>
2019-01-01 00:00:18

**We must preserve the cyclical nature of time within a day, and days within a year.  We will address this in the *Clean Up* section.**

**Now look at *cc_num*.**

In [9]:
pd.set_option('display.max_rows', None)  # or 1000
print(df.loc[df['is_fraud'] == 1, 'cc_num'].value_counts())
pd.set_option('display.max_rows', 10)  # or 1000

4593569795412          19
4599285557366057       19
3520550088202337       19
6538441737335434       18
4260128500325          18
4874006077381178       16
6538891242532018       16
213112402583773        16
4725837176265195730    16
3577794103155425       16
4400011257587661852    16
3576021480694169       16
3556613125071656       16
4629451965224809       16
3518669219150142       16
6011366578560244       16
3589289942931264       16
3575540972310993       16
30074693890476         16
2227671554547514       16
2720433095629877       16
30011465039817         16
2229824890647120       15
30501624614310         15
676326610042           15
4633065159406313       15
3519232971341141       15
4586260469584          15
375974680629816        15
30270432095985         15
36721445180895         15
5289285402893489       15
370612217861404        15
6506116513503136       15
3521260686633367       15
3567879740649740       15
675945690716           15
501851115094           15
2248348993063230       15
5388659976630693       15
6011693194885790       15
342360239917375        15
3501942333500073       15
4210078554961359092    15
3523843138706408       15
6011382886333463       15
4904681492230012       15
6597248210463122       15
675990301623           15
5154903938030655       15
376445266762684        15
2242542703101233       15
341546199006537        15
3528231451607350       15
4294930380592          15
4168696938629925       15
4926376199189801       15
4364010865167176       15
4989847570577635369    15
3598014571045296       15
36890292963032         15
3534093764340240       15
4294040533480516       15
2383461948823908       15
371226440126102        15
3500969075198072       15
630425673344           15
4334230547694630       15
3527536963490470       15
30199621383748         15
180084576295055        15
6534628260579800       15
213174467670432        15
213180742685905        15
3517527805128735       14
4561368699336875       14
30442439074871         14
6011438889172900       14
30518206766474         14
4048508450704760       14
60427851591            14
213102873001603        14
639023984367           14
4761403817546679245    14
4653879239169997       14
4181833256558613886    14
180048185037117        14
4266200684857219       14
4797297220948468262    14
3573030041201292       14
2610529083834453       14
6011552879910390       14
4783226709001          14
571314334723           14
4301028321766222513    14
4917226033950          14
3529597930342630       14
2222001896600109       14
630424987505           14
38295635583927         14
375082648741747        14
4026222041577          14
4990494243023          14
4587577161160601       14
3506042666828517       14
3537797820923602       14
676148621961           14
180031190491743        14
3544606805704278       14
4451952084362894       14
4789911625179723       14
4555104582813474       14
3529597810116815       14
3596217206093829       14
213154573301411        14
4446368897795790       14
3547574373318979       14
676275912597           14
3588001568691267       14
4430881574719618       14
344709867813900        14
213157767990030        14
341542810616333        14
4010002218955876       14
4855488158131690372    14
4710826438164847414    14
4424338559877976       14
4488941175228467       14
502012776709           14
3562264947797243       14
4806443445305          13
342319985983023        13
675961917837           13
4607072969078276       13
4259996134423          13
4560395181594436016    13
3559679414981506       13
3566875419572867       13
375534208663984        13
374238209524200        13
38199021865320         13
676372984911           13
4810789809665942990    13
5559857416065248       13
377234009633447        13
3562793934111141       13
4365382885912355       13
6011581063717667       13
4879265611163287       13
3545109339866548       13
3533800906065217       13
371284100299909        13
4335531783520911       13
4208110975550360171    13
349612764943496        13
676118385837           13
30446018552504         13
2283743876903625       13
4204237326785494       13
3527063666782582       13
373905417449658        13
2297447006766555       13
3585052663373890       13
4279161831637          13
3531129874770000       13
4067137330196900       13
4512828414983801773    13
30033162392091         13
3554818239968984       13
4500002361389          13
347612609554823        13
372382441451095        13
213155997615567        13
570273151375           13
2231186809828225       12
3513285035244624       12
3524574586339330       12
4040099974063068803    12
4189814094741          12
5540636818935089       12
3561212938177173       12
6011948324228984       12
3565943051129759       12
2706977570537524       12
180098888332620        12
4501449508569485       12
4198470814557          12
4536996888716062123    12
4239436242473          12
4092452671396169678    12
3560697798177746       12
4433091568498503       12
4223708906367574214    12
3567527758368741       12
676308307625           12
2450829271795901       12
4957924165498          12
4651007077623147       12
4260059589824237       12
4855853415727304322    12
4538566639857          12
3502088871723054       12
3565414434959494       12
4254074738931278       12
4897067971111209737    12
2719496466799416       12
30499715231997         12
4450831335606294       12
4629125581019          12
4355790796238264643    12
2291163933867244       12
378858024506425        12
2288748891690227       12
503848303379           12
180067784565096        12
38530489946071         12
340953839692349        12
30510856607165         12
180094608895855        12
180020605265701        12
3546436741611231       12
60495593109            12
586100864972           12
3562679455732797       12
676369110710           12
571844099986           12
4025612008285111       12
571465035400           12
676292294938           12
376656886990758        12
4659625317833446364    12
577891228931           12
180049032966888        12
2229378226512508       12
4220345354880          12
4922710831011201       12
4736845434667908128    12
30364087349027         12
5130484058948421       12
180040027502291        12
3595192916105588       12
4642255475285942       12
30044330818990         12
4302480582202074       12
3541554378551366       12
377993105397617        12
3542162746848552       12
3587044315915002       12
180046165512893        12
30546453310167         12
378006354724784        12
4687263141103          12
30487648872433         12
4601636330889          12
4103158249977          12
4623560839669          12
4939976756738216       12
343819048608995        12
4518350514020532       12
4099707841315751       12
180014262259255        12
3543299015720986       12
3519607465576254       12
3540862542587229       12
3548710338694745       12
60422928733            12
30238755902988         12
4988304376504          12
378278619832195        12
38014427445058         12
3534330126107879       12
4195740185974          12
4428780983793657331    12
501882822387           12
3599237318576484       12
30131826429364         12
30197398657930         12
4076173495454          12
180052752563109        12
36192615525683         12
6569097840281287       12
6011975266774121       12
4585132874641          12
6524376634971418       12
3589255887819806       12
38052002992326         11
3557442674264531       11
4128027264554082       11
4550599031376731       11
371009169330125        11
30376238035123         11
3502377050801561       11
30235438713303         11
4997733566924489       11
676298633337           11
3517814635263522       11
3526826139003047       11
676179782773           11
2512312531485080       11
4760122961662          11
5127412150261034       11
4509922033272157       11
6554245334757802       11
4715741951931168360    11
6011542681743618       11
3514865930894695       11
3511378610369890       11
3528040995648998       11
6517779374888867       11
3546674063249004       11
581293083266           11
6526777409109795       11
4906628655840914250    11
3524485462198080       11
4561892980175          11
3525668150756629       11
3533177016567295       11
30135235368675         11
675909898057           11
6011935564104173       11
4457732997086323466    11
4169759661243568       11
374497717543058        11
342952484382519        11
4124536010991657       11
30143713661454         11
213161293389774        11
3547336099599450       11
4383521454815          11
6011148190095209       11
3550412175018089       11
2720894374956739       11
4180192513916047166    11
4417677808209716       11
5301645381939419       11
3501365119557234       11
4658490815480264       11
30560609640617         11
4661996144291811856    11
3536818734263520       11
4933461930348832       11
676245600876           11
6011348830550197       11
4961003488432306       11
4079773899158          11
2703186189652095       11
2454076758463217       11
3530503964418806       11
30029052116970         11
4713464490314802       11
6593939509150446       11
4716561796955522       11
342035762534413        11
4859525594182537       11
6526955903501879       11
639046421587           11
2348245054386329       11
4666314527820883145    11
4979422371139333       11
372246459334925        11
340951438290556        11
373213026644490        11
3513506355699497       11
3575789281659026       11
3543591270174051       11
3560797065840735       11
378262805520186        11
2475085306462014       11
4740713119940984       11
213125815021702        11
573860193545           11
3587960728692500       11
4492677353108006       11
3543885983111461       11
3583093681934489       11
3541687240161491       11
565399283797           11
30230540139182         11
6515067575568369       11
6011681934117244       11
375848982312810        11
4841313716651064       11
4220495028289516646    11
30143535920989         11
30103132002433         11
345933964507467        11
2318062975163331       11
3593399694467427       11
4800395067176717       11
340214844585279        11
3565196229855512       11
3561963695236764       11
3508104404056005       11
4777065439639721       11
6011679934075347       11
3531606252458308       11
345832460465610        11
3586008444788268       11
6517217825320610       11
3549202406645667       11
4426075337087318654    11
4562827002127          11
377895991033232        11
4306586894261180       10
30042378430132         10
3534718226968689       10
2296006538441789       10
630471368021           10
3541160328600277       10
3559723917628303       10
4158008602445          10
3565996340207976       10
4462038234743679432    10
580954173374           10
4980323467523543940    10
374125201044065        10
3592325941359225       10
3504178999463051       10
2285066385084291       10
2714019737356678       10
6011492816282597       10
4384910379661778       10
4158758517677931       10
3591919803438423       10
4412720572684931       10
6011626928491360       10
3564182536169293       10
4893092478075970       10
377834944388609        10
4129767952109660       10
180068353086472        10
3586955669388457       10
371034293500716        10
4698163635895795       10
377026671291680        10
375237305371366        10
3542826960473004       10
4476840372112          10
346243940647414        10
343668971234893        10
4119762878330989       10
6595970453799027       10
30290551782700         10
4005676619255478       10
213161231269724        10
3598304579370089       10
4657269323674365       10
6573561108825071       10
6596735789587928       10
3568736585751727       10
4170689372027579       10
347399333635231        10
6011477612335392       10
372965408103277        10
4745996322265          10
503851367360           10
4427805710168          10
374930071163758        10
3529788038921264       10
3558652751678952       10
4344955088481397       10
4748866581408          10
375623337201129        10
341283058448499        10
4492491748959010       10
6011518448009279       10
2242176657877538       10
180038493344495        10
3533742182628021       10
4162872756672112717    10
36153880429415         10
4764202053279782       10
345225948700767        10
2305336922781618       10
3540210836308425       10
180065479077096        10
4669558618943766       10
5580563567307107       10
630451534402           10
676309913934           10
3577663406369449       10
4956828990005111019    10
4449530933957323       10
4844243189971          10
2269768987945882       10
2256234701263057       10
180036456789979        10
6011231546538393       10
4973530368125489546    10
371683116218417        10
60423098130            10
213136802746375        10
2295963260374698       10
6011706277606006       10
6597888193422452       10
3598634130286287       10
4110266553600176127    10
2356276337669917       10
5144043920225212       10
4393520897625          10
4006047418382          10
2657850734909997       10
6550399784335736       10
4642894980163          10
3552581383553463       10
2720830304681674       10
38797410705641         10
581686439828           10
4265776278887457       10
4457486401506          10
180064817343047        10
4586810168620942       10
6011934240159560       10
571365235126           10
4822367783500458       10
676234256292           10
4257110907449569602    10
4826655832045236       10
60490596305            10
5596347693144598       10
561942763351           10
2254917871818484       10
4952583804639909       10
4575255480814133        9
3501285649323933        9
676173792455            9
3576281490078437        9
6011197122270059        9
30371006069917          9
3576144910346950        9
213198837352314         9
30596478689301          9
180058696935600         9
6592861994408652        9
30153452207526          9
30373802285317          9
373043435942726         9
343746486082492         9
30408301059761          9
213186334552049         9
4379260813815979609     9
345389171551808         9
376944481517097         9
4063094974360571498     9
3501509250702469        9
348789608637806         9
4003771737807706        9
6011393492413821        9
3563837241599446        9
6011826317034777        9
3565423334076143        9
38057513087029          9
4318414072191879        9
3597337756918966        9
4502539526809429801     9
3581130339108561        9
6544734391390261        9
3518758680062249        9
30263540414123          9
3590946339258737        9
3553629419254918        9
583699482621            9
4469777115158234880     9
2260801330657968        9
6011099828110011        9
4951647200979051        9
4239552724014407        9
503886119844            9
213173753804333         9
4769426683924058915     9
213186880359195         9
4225990116481262579     9
3540075240003197        9
3506040590383211        9
376262134119629         9
30344654314976          9
4243521033756702612     9
4171397999167005        9
180069253480336         9
3514897282719543        9
4149238353975790        9
4186530744674           9
6011399591920186        9
30428204673351          9
3576207763781753        9
2287277963630565        9
4358137750029944984     9
3559160581764413        9
213161869125933         9
4045036286570100739     9
4969856774088583        9
4683638447911           9
3592931352252641        9
38534201672254          9
4087542780207162        9
4116554952971686        9
676281772837            9
345060451158891         9
4883407061576           9
180017442990269         9
30082025922891          9
4481131401752           9
378904938837132         9
503874407318            9
30570197515105          9
347073228412010         9
2264937662466770        9
676248282243            9
6506982560413523        9
180047222886866         9
4244953610136705533     9
4488258847705225890     9
4134456652433447        9
4209696857872688515     9
3558881852140592        9
3597980945245815        9
3536918668124647        9
3511058278399773        9
30030380240193          9
2266735643685262        9
213156747557083         9
3525590521269779        9
4598025465633           9
5410056176712193        9
502038091380            9
3582402971899057        9
30235268718158          9
180067151859700         9
180040131978916         9
4710792708725663        9
581508178315            9
30561214688470          9
4861310130652566408     9
370348764075623         9
6011305591981276        9
60416207185             9
4824023901222438        9
560881134780            9
4060579726528237        9
4911818930706644725     9
30434173205605          9
568279015842            9
346208242862904         9
30248898834493          9
4173950183554608        9
4308156300921054        9
4998109455173950        9
6547670341037171        9
4312133045694601139     9
6500249000784905        9
36581538659449          9
6011999606625827        9
4653178848915023204     8
4670613943676271        8
4229733778084049        8
3583793405872580        8
4634955908138648        8
38588538868506          8
4972228199573984        8
3535808924394848        8
38817501916673          8
501828204849            8
4464457352619           8
3550554389581384        8
343472729187663         8
630469040731            8
4155021259183870        8
4247921790666           8
3512365128314616        8
180072527505094         8
577588686219            8
4292743669224718067     8
4373370572092720777     8
4509142395811241        8
4302475216404898        8
180042946491150         8
38859492057661          8
4306630852918           8
3579200383632826        8
344342339068828         8
4104312520615374        8
501899453424            8
5456712664803820        8
6011603272871604        8
630412733309            8
4635330563105903        8
4157213332670159        8
180056173248083         8
4003989662068504        8
3540416671210051        8
180011453250192         8
213195754007681         8
180046617132290         8
376028110684021         8
3593118134380341        8
4788103653396           8
573283817795            8
4646845581490336108     8
6502195877055606        8
348253506557335         8
6564459919350820        8
3560725013359375        8
4482427013979020        8
213193596103206         8
60487002085             8
4599735407877245080     8
4873783502705038        8
6540981358631302        8
4613314721966           8
3567697931646329        8
213113338379864         8
4605902936394           8
2716017661090253        8
639030014711            8
6539653032686894        8
4292902571056973207     8
4935858973307492        8
4228411452607671        8
4457136361520330110     8
3540017235499519        8
6011149206456997        8
343464013864032         8
213148039875802         8
4561546772499           8
374656033243756         8
4477156602511939689     8
4756039869079882102     8
4396682467723           8
676327197445            8
3523898249167098        8
6535328428560433        8
5501083170975659        8
3577596616955856        8
501818133297            8
3521815216091574        8
5104807169438134        8
377264520876399         8
4683520018489354        8
501831082224            8
630484879808            8
4839043708100390        8
213178850083780         8
180046765320457         8
3535211949888417        8
4890424426862856940     8
2235335206132667        8
30357372465631          8
375767678113375         8
3590736522064285        8
4560004149983868183     8
4839615922685395        8
2720012583106919        8
6526448584969862        8
2713913904780408        8
372509258176510         8
379141394109214         8
30427035050508          8
4378993458389626        8
30175986190993          8
4452366298769043        8
4390966588600992777     8
30273037698427          8
3585740823295298        8
3560246577314524        8
213163860545705         8
676195318214            8
4467456915153312231     8
4319584480204988982     8
4658117080136           8

***cc_num* seems to show no pattern with *is_fraud*; because there are so many different values, we will later drop this column rather than one-hot-encode.**  
**We will move on to *merchant*.**

In [10]:
pd.set_option('display.max_rows', None)  # or 1000
print((df.loc[df['is_fraud'] == 1, 'merchant'].value_counts() /\
       df['merchant'].value_counts()).sort_values(ascending=False))
pd.set_option('display.max_rows', 10)  # or 1000

fraud_Kozey-Boehm                              0.021755
fraud_Herman, Treutel and Dickens              0.020321
fraud_Terry-Huel                               0.019553
fraud_Kerluke-Abshire                          0.018975
fraud_Mosciski, Ziemann and Farrell            0.018788
fraud_Schmeler, Bashirian and Price            0.018651
fraud_Kuhic LLC                                0.018649
fraud_Jast Ltd                                 0.018498
fraud_Langworth, Boehm and Gulgowski           0.018459
fraud_Romaguera, Cruickshank and Greenholt     0.018432
fraud_Boyer-Reichert                           0.018352
fraud_Heathcote, Yost and Kertzmann            0.018306
fraud_Goyette Inc                              0.018031
fraud_Lemke-Gutmann                            0.017921
fraud_Medhurst PLC                             0.017480
fraud_Rau and Sons                             0.016920
fraud_Heathcote LLC                            0.016919
fraud_Durgan-Auer                              0.016793
fraud_Greenholt, O'Hara and Balistreri         0.016770
fraud_Moore, Dibbert and Koepp                 0.016757
fraud_Bednar Group                             0.016667
fraud_Kuhic, Bins and Pfeffer                  0.016637
fraud_Price Inc                                0.016637
fraud_Gleason-Macejkovic                       0.016586
fraud_Kerluke, Kertzmann and Wiza              0.016487
fraud_Stanton, Jakubowski and Baumbach         0.016439
fraud_Doyle Ltd                                0.016276
fraud_Brown PLC                                0.016120
fraud_Miller-Harris                            0.016013
fraud_Kris-Weimann                             0.015945
fraud_Labadie, Treutel and Bode                0.015902
fraud_Schmidt and Sons                         0.015884
fraud_Stamm-Witting                            0.015844
fraud_Bashirian Group                          0.015809
fraud_Rempel Inc                               0.015803
fraud_Gottlieb, Considine and Schultz          0.015748
fraud_Moen, Reinger and Murphy                 0.015620
fraud_Fisher-Schowalter                        0.015498
fraud_Towne, Greenholt and Koepp               0.015451
fraud_McGlynn-Heathcote                        0.015427
fraud_Mante Group                              0.015358
fraud_Schultz, Simonis and Little              0.015348
fraud_Baumbach, Feeney and Morar               0.015184
fraud_Streich, Dietrich and Barton             0.015168
fraud_Volkman Ltd                              0.015143
fraud_Tillman, Fritsch and Schmitt             0.015119
fraud_Padberg-Welch                            0.015103
fraud_Fisher Inc                               0.015093
fraud_Kihn, Abernathy and Douglas              0.014936
fraud_Nader-Heller                             0.014908
fraud_Parisian, Schiller and Altenwerth        0.014876
fraud_Kiehn-Emmerich                           0.014829
fraud_Bogisich-Homenick                        0.014786
fraud_Koelpin and Sons                         0.014698
fraud_Auer-West                                0.014680
fraud_Kuphal-Bartoletti                        0.014650
fraud_Altenwerth, Cartwright and Koss          0.014519
fraud_McDermott-Weimann                        0.014518
fraud_Vandervort-Funk                          0.014493
fraud_Kassulke PLC                             0.014461
fraud_Rohan, White and Aufderhar               0.014436
fraud_Rodriguez, Yost and Jenkins              0.014404
fraud_Koepp-Witting                            0.014391
fraud_Jaskolski-Vandervort                     0.014278
fraud_Mohr-Bayer                               0.014250
fraud_Murray-Smitham                           0.014155
fraud_Reichert, Huels and Hoppe                0.014141
fraud_Donnelly PLC                             0.014107
fraud_Reichert, Rowe and Mraz                  0.014058
fraud_Stracke-Lemke                            0.013944
fraud_Gerlach Inc                              0.013869
fraud_Kiehn Inc                                0.013853
fraud_Kerluke, Considine and Macejkovic        0.013691
fraud_Flatley-Durgan                           0.013613
fraud_Strosin-Cruickshank                      0.013596
fraud_Kunze Inc                                0.013579
fraud_Rippin, Kub and Mann                     0.013575
fraud_Welch Inc                                0.013557
fraud_Hudson-Ratke                             0.013502
fraud_Bailey-Morar                             0.013475
fraud_Lockman, West and Runte                  0.013307
fraud_Miller-Hauck                             0.013303
fraud_Huel, Hammes and Witting                 0.013228
fraud_Schmitt Ltd                              0.013172
fraud_Zboncak, Rowe and Murazik                0.013167
fraud_Kerluke Inc                              0.013136
fraud_Little, Gutmann and Lynch                0.013130
fraud_Lockman Ltd                              0.013128
fraud_Osinski, Ledner and Leuschke             0.012925
fraud_Hills-Witting                            0.012910
fraud_Wolf Inc                                 0.012861
fraud_O'Keefe-Hudson                           0.012744
fraud_Zemlak Group                             0.012712
fraud_Schumm, Bauch and Ondricka               0.012644
fraud_Mosciski, Gislason and Mertz             0.012636
fraud_Volkman-Predovic                         0.012631
fraud_Ankunding LLC                            0.012581
fraud_Bernier, Volkman and Hoeger              0.012479
fraud_Klocko LLC                               0.012446
fraud_Bradtke PLC                              0.012391
fraud_Koepp-Parker                             0.012353
fraud_Cole PLC                                 0.012353
fraud_Goldner, Kovacek and Abbott              0.012291
fraud_Lebsack and Sons                         0.012286
fraud_Reichert, Shanahan and Hayes             0.012233
fraud_Pacocha-O'Reilly                         0.012055
fraud_Auer-Mosciski                            0.012045
fraud_Block-Parisian                           0.011784
fraud_Goodwin-Nitzsche                         0.011673
fraud_Hayes, Marquardt and Dibbert             0.011589
fraud_Barton Inc                               0.011438
fraud_DuBuque LLC                              0.011438
fraud_Ferry, Lynch and Kautzer                 0.011438
fraud_Bauch-Raynor                             0.011398
fraud_Cartwright-Harris                        0.011321
fraud_Predovic Inc                             0.011295
fraud_Deckow-O'Conner                          0.011242
fraud_Kuhic Inc                                0.011223
fraud_Ruecker Group                            0.011211
fraud_Schoen, Kuphal and Nitzsche              0.011170
fraud_Huel-Langworth                           0.011129
fraud_Schamberger-O'Keefe                      0.011033
fraud_Kunde-Sanford                            0.011031
fraud_Kuphal-Predovic                          0.011025
fraud_Boyer PLC                                0.011002
fraud_Kuhn LLC                                 0.010932
fraud_Corwin-Gorczany                          0.010730
fraud_Casper, Hand and Zulauf                  0.010695
fraud_Stehr, Jewess and Schimmel               0.010626
fraud_Heidenreich PLC                          0.010563
fraud_Hackett-Lueilwitz                        0.010480
fraud_Rowe, Batz and Goodwin                   0.010336
fraud_Rutherford-Mertz                         0.010262
fraud_Kovacek Ltd                              0.010256
fraud_Lehner, Mosciski and King                0.010182
fraud_Kutch and Sons                           0.010149
fraud_Kerluke PLC                              0.010147
fraud_Cormier LLC                              0.010103
fraud_Bogisich Inc                             0.010017
fraud_Heller, Gutmann and Zieme                0.009921
fraud_Kilback LLC                              0.009901
fraud_Ruecker, Beer and Collier                0.009883
fraud_Kovacek, Dibbert and Ondricka            0.009629
fraud_Dooley-Thompson                          0.009572
fraud_Huel Ltd                                 0.009380
fraud_Stoltenberg-Beatty                       0.009354
fraud_Quitzon, Green and Bashirian             0.009229
fraud_Beier-Hyatt                              0.009048
fraud_Johnson, Runolfsdottir and Mayer         0.008825
fraud_Sawayn PLC                               0.007995
fraud_Macejkovic-Lesch                         0.007912
fraud_Schumm PLC                               0.007892
fraud_Hamill-Daugherty                         0.007852
fraud_Swift, Bradtke and Marquardt             0.007825
fraud_Jones, Sawayn and Romaguera              0.007782
fraud_Baumbach, Hodkiewicz and Walsh           0.007690
fraud_Dooley Inc                               0.007650
fraud_Barrows PLC                              0.007643
fraud_Conroy Ltd                               0.007573
fraud_Turner and Sons                          0.007508
fraud_Dach-Nader                               0.007295
fraud_Nitzsche, Kessler and Wolff              0.007275
fraud_Pouros-Haag                              0.007149
fraud_Greenfelder, Bartoletti and Davis        0.007100
fraud_Douglas, Schneider and Turner            0.007049
fraud_Haley, Jewess and Bechtelar              0.006926
fraud_Watsica, Haag and Considine              0.006892
fraud_Pacocha-Bauch                            0.006874
fraud_Jacobi and Sons                          0.006868
fraud_Mayert Group                             0.006841
fraud_Hermann and Sons                         0.006839
fraud_Parisian and Sons                        0.006773
fraud_Goyette, Howell and Collier              0.006707
fraud_Torphy-Goyette                           0.006697
fraud_Denesik and Sons                         0.006675
fraud_Lynch Ltd                                0.006675
fraud_Pfeffer and Sons                         0.006667
fraud_Bahringer, Schoen and Corkery            0.006641
fraud_Botsford Ltd                             0.006609
fraud_Mohr Inc                                 0.006581
fraud_Prohaska-Murray                          0.006563
fraud_Jewess LLC                               0.006548
fraud_Schuppe, Nolan and Hoeger                0.006469
fraud_Tromp Group                              0.006206
fraud_Conroy-Cruickshank                       0.006179
fraud_Swaniawski, Lowe and Robel               0.005912
fraud_Koss and Sons                            0.005854
fraud_Pagac LLC                                0.005735
fraud_Weimann, Kuhic and Beahan                0.005689
fraud_Hickle Group                             0.005645
fraud_Pouros-Conroy                            0.005630
fraud_Baumbach, Strosin and Nicolas            0.005486
fraud_Lesch Ltd                                0.005432
fraud_Kris-Padberg                             0.005410
fraud_Schmitt Inc                              0.005338
fraud_Kihn Inc                                 0.005336
fraud_Jast-McDermott                           0.005276
fraud_Okuneva, Schneider and Rau               0.005152
fraud_Greenholt, Jacobi and Gleason            0.005008
fraud_Eichmann, Bogan and Rodriguez            0.005003
fraud_Jenkins, Hauck and Friesen               0.004978
fraud_Heller-Langosh                           0.004934
fraud_Cummerata-Jones                          0.004922
fraud_Reilly, Heaney and Cole                  0.004867
fraud_Kuvalis Ltd                              0.004865
fraud_Bernhard Inc                             0.004812
fraud_Roob, Conn and Tremblay                  0.004798
fraud_Bins-Rice                                0.004757
fraud_Kutch LLC                                0.004702
fraud_Willms, Kris and Bergnaum                0.004695
fraud_VonRueden Group                          0.004680
fraud_Johnston, Nikolaus and Maggio            0.004619
fraud_Spinka-Welch                             0.004598
fraud_Hahn, Douglas and Schowalter             0.004583
fraud_Tillman, Dickinson and Labadie           0.004538
fraud_Boehm, Predovic and Reinger              0.004507
fraud_Daugherty, Pouros and Beahan             0.004495
fraud_Roob LLC                                 0.004491
fraud_Christiansen, Goyette and Schamberger    0.004481
fraud_Kutch-Hegmann                            0.004478
fraud_Bernier, Streich and Jewess              0.004435
fraud_Ferry, Reichel and DuBuque               0.004431
fraud_Balistreri-Nader                         0.004405
fraud_Harber Inc                               0.004396
fraud_Spencer-Runolfsson                       0.004376
fraud_Champlin, Rolfson and Connelly           0.004374
fraud_Lemke and Sons                           0.004363
fraud_Schaefer, Maggio and Daugherty           0.004358
fraud_Kozey-McDermott                          0.004340
fraud_Ankunding-Carroll                        0.004329
fraud_Robel, Cummerata and Prosacco            0.004323
fraud_Luettgen PLC                             0.004302
fraud_Mosciski Group                           0.004284
fraud_Haley Group                              0.004274
fraud_Friesen Inc                              0.004267
fraud_Bernhard, Grant and Langworth            0.004262
fraud_Ritchie, Oberbrunner and Cremin          0.004244
fraud_Friesen-Stamm                            0.004240
fraud_Eichmann, Hayes and Treutel              0.004237
fraud_Bartoletti-Wunsch                        0.004218
fraud_Erdman-Kertzmann                         0.004168
fraud_Ziemann-Waters                           0.004102
fraud_Cremin, Hamill and Reichel               0.004085
fraud_Stark-Batz                               0.004071
fraud_Cummings LLC                             0.004031
fraud_Ledner-Pfannerstill                      0.003985
fraud_Stiedemann Inc                           0.003974
fraud_Hudson-Grady                             0.003972
fraud_Wisozk and Sons                          0.003956
fraud_Stroman, Hudson and Erdman               0.003917
fraud_Metz-Boehm                               0.003912
fraud_Rodriguez Group                          0.003903
fraud_Corwin-Collins                           0.003893
fraud_Halvorson Group                          0.003893
fraud_Collier Inc                              0.003876
fraud_Jaskolski-Dibbert                        0.003870
fraud_Shields Inc                              0.003870
fraud_Effertz LLC                              0.003846
fraud_Gutmann Ltd                              0.003846
fraud_Marks Inc                                0.003843
fraud_Murray Ltd                               0.003802
fraud_Huels-Nolan                              0.003770
fraud_Spinka Inc                               0.003765
fraud_Hills-Boyer                              0.003755
fraud_Ratke and Sons                           0.003699
fraud_Connelly, Reichert and Fritsch           0.003696
fraud_Mraz-Herzog                              0.003696
fraud_Adams, Kovacek and Kuhlman               0.003693
fraud_Olson, Becker and Koch                   0.003678
fraud_Gislason Group                           0.003656
fraud_Satterfield-Lowe                         0.003653
fraud_Gutmann-Upton                            0.003607
fraud_Thiel PLC                                0.003584
fraud_Herman Inc                               0.003575
fraud_Reynolds-Schinner                        0.003571
fraud_Nicolas, Hills and McGlynn               0.003564
fraud_Turner, Ruecker and Parisian             0.003556
fraud_Dickinson-Rempel                         0.003548
fraud_Morissette PLC                           0.003539
fraud_Bruen-Yost                               0.003530
fraud_Harris Inc                               0.003514
fraud_Buckridge PLC                            0.003512
fraud_Schaefer, McGlynn and Bosco              0.003474
fraud_Smith-Stokes                             0.003469
fraud_Boyer-Haley                              0.003460
fraud_Kassulke Inc                             0.003460
fraud_Torp-Labadie                             0.003449
fraud_Monahan, Hermann and Johns               0.003442
fraud_Streich, Hansen and Veum                 0.003435
fraud_Christiansen-Gusikowski                  0.003433
fraud_Langworth LLC                            0.003430
fraud_Hermann-Gaylord                          0.003422
fraud_Gibson-Deckow                            0.003400
fraud_Crooks and Sons                          0.003398
fraud_Kling Inc                                0.003385
fraud_Stamm-Rodriguez                          0.003384
fraud_Emard Inc                                0.003362
fraud_Fritsch LLC                              0.003347
fraud_Hagenes, Hermann and Stroman             0.003336
fraud_Bins, Balistreri and Beatty              0.003312
fraud_Abshire PLC                              0.003293
fraud_Ledner, Hartmann and Feest               0.003284
fraud_Block-Hauck                              0.003255
fraud_Corwin-Romaguera                         0.003249
fraud_Lind, Huel and McClure                   0.003231
fraud_Hilpert-Conroy                           0.003220
fraud_Heller-Abshire                           0.003187
fraud_Brekke and Sons                          0.003174
fraud_Abbott-Steuber                           0.003163
fraud_Fahey Inc                                0.003154
fraud_Emmerich-Luettgen                        0.003140
fraud_Watsica LLC                              0.003138
fraud_Huels-Hahn                               0.003129
fraud_Wuckert-Walter                           0.003110
fraud_Bins-Howell                              0.003109
fraud_Homenick LLC                             0.003103
fraud_Harris, Gusikowski and Heaney            0.003091
fraud_Cassin-Harvey                            0.003086
fraud_Schneider, Hayes and Nikolaus            0.003065
fraud_Keeling-Crist                            0.003057
fraud_Terry, Johns and Bins                    0.003050
fraud_Leffler-Goldner                          0.003046
fraud_Wiza LLC                                 0.003037
fraud_Dare-Marvin                              0.003029
fraud_Lehner, Reichert and Mills               0.003029
fraud_Cormier, Stracke and Thiel               0.003021
fraud_Wintheiser, Dietrich and Schimmel        0.003019
fraud_Towne, Walker and Borer                  0.003003
fraud_Spencer PLC                              0.002994
fraud_Kling-Grant                              0.002994
fraud_Wilkinson Ltd                            0.002976
fraud_Yost, Block and Koepp                    0.002972
fraud_Cruickshank-Mills                        0.002972
fraud_Reichel Inc                              0.002935
fraud_Raynor, Reinger and Hagenes              0.002923
fraud_Berge LLC                                0.002905
fraud_Runte, Green and Emard                   0.002905
fraud_Dare, Casper and Bartoletti              0.002840
fraud_Larkin Ltd                               0.002838
fraud_Bahringer, Bergnaum and Quitzon          0.002815
fraud_Streich, Rolfson and Wilderman           0.002801
fraud_Schiller, Blanda and Johnson             0.002789
fraud_Bode-Schuster                            0.002763
fraud_Friesen-D'Amore                          0.002747
fraud_Reichel LLC                              0.002734
fraud_Shanahan-Lehner                          0.002731
fraud_Douglas, DuBuque and McKenzie            0.002725
fraud_Rolfson-Kunde                            0.002715
fraud_Monahan, Bogisich and Ledner             0.002699
fraud_Erdman-Ebert                             0.002693
fraud_Parker-Kunde                             0.002689
fraud_Zieme, Bode and Dooley                   0.002688
fraud_Kozey-Kuhlman                            0.002686
fraud_Baumbach Ltd                             0.002685
fraud_Kessler Group                            0.002681
fraud_Bradtke, Torp and Bahringer              0.002669
fraud_Howe PLC                                 0.002663

***merchant* seems to show no pattern with *is_fraud*; because there are so many different values, we will later drop this column rather than one-hot-encode.**  

**Now we will examine *category*.**

In [11]:
df['category'].unique()

array(['misc_net', 'grocery_pos', 'entertainment', 'gas_transport',
       'misc_pos', 'grocery_net', 'shopping_net', 'shopping_pos',
       'food_dining', 'personal_care', 'health_fitness', 'travel',
       'kids_pets', 'home'], dtype=object)

**We will later one-hot-encode *category*.**
  
**We will later drop *first* and *last* names since they are essentially unique per data point.**  
**We will later one-hot-encode *sex* since it is categorical.**  
**We will later drop *street* since *zip*, *city*, and *state* are more meaningful categorical features for location.**  
**We will now examine *zip*.**

In [12]:
pd.set_option('display.max_rows', None)  # or 1000
print((df.loc[df['is_fraud'] == 1, 'zip'].value_counts() /\
       df['zip'].value_counts()).sort_values(ascending=False))
pd.set_option('display.max_rows', 10)  # or 1000

99921    1.000000
10533    1.000000
47842    1.000000
48054    1.000000
48436    1.000000
52658    1.000000
53045    1.000000
53559    1.000000
14532    1.000000
54980    1.000000
55040    1.000000
14141    1.000000
13795    1.000000
61364    1.000000
62896    1.000000
63966    1.000000
12508    1.000000
64080    1.000000
65745    1.000000
66958    1.000000
12207    1.000000
67346    1.000000
68375    1.000000
11944    1.000000
11763    1.000000
11747    1.000000
70065    1.000000
70447    1.000000
72135    1.000000
10954    1.000000
10553    1.000000
46510    1.000000
46060    1.000000
43723    1.000000
19947    1.000000
23523    1.000000
22204    1.000000
22124    1.000000
27051    1.000000
28033    1.000000
28119    1.000000
28412    1.000000
28530    1.000000
21657    1.000000
29129    1.000000
29180    1.000000
32065    1.000000
33762    1.000000
35211    1.000000
16041    1.000000
35896    1.000000
18446    1.000000
37307    1.000000
37411    1.000000
37683    1.000000
37887    1.000000
38668    1.000000
38915    1.000000
39562    1.000000
16428    1.000000
40502    1.000000
16214    1.000000
41101    1.000000
73044    1.000000
56367    1.000000
23117    1.000000
75246    1.000000
87417    1.000000
89109    1.000000
90240    1.000000
78644    1.000000
78208    1.000000
77038    1.000000
93427    1.000000
77027    1.000000
94508    1.000000
4032     1.000000
76048    1.000000
80019    1.000000
95688    1.000000
85201    1.000000
98105    1.000000
97850    1.000000
74108    1.000000
99116    1.000000
10018    1.000000
98118    1.000000
99747    1.000000
32565    0.021534
12037    0.021534
52760    0.021477
33760    0.021477
48193    0.020243
30426    0.020188
59632    0.020188
12092    0.020188
50598    0.020188
97107    0.020161
39572    0.020161
24986    0.020161
2908     0.020134
98836    0.018919
11955    0.018893
15458    0.018868
40062    0.018868
37138    0.018868
18246    0.018868
6365     0.018868
36775    0.018843
73624    0.018843
62266    0.018817
49629    0.018817
75934    0.017568
74720    0.017568
65066    0.017544
31630    0.017544
63533    0.017544
63388    0.017520
31003    0.017520
68438    0.017497
45638    0.017497
4953     0.017497
54499    0.016327
18357    0.016327
35131    0.016304
25832    0.016260
47869    0.016238
48154    0.016238
87109    0.016238
50595    0.016238
80014    0.016238
53910    0.016238
10162    0.016238
36853    0.016216
20882    0.016216
22719    0.016216
57439    0.016216
56117    0.016216
87116    0.016216
79343    0.016216
89704    0.016194
31092    0.016194
69201    0.016194
97492    0.016194
21405    0.016173
23666    0.016173
56029    0.016173
39653    0.016173
82190    0.016173
38949    0.016173
75210    0.016173
24236    0.014946
66616    0.014925
88256    0.014925
57641    0.014925
97910    0.014925
31561    0.014905
44804    0.014905
92101    0.014905
2180     0.014905
36532    0.014885
14479    0.014885
56672    0.014885
63353    0.014885
20017    0.014885
91702    0.014885
11419    0.014865
23106    0.014865
43136    0.014865
68869    0.014865
50314    0.014865
93552    0.014865
40209    0.014845
34120    0.014845
23357    0.013624
72354    0.013605
3774     0.013587
92267    0.013587
96136    0.013569
14445    0.013569
3858     0.013569
72751    0.013569
24878    0.013550
68117    0.013550
73719    0.013550
86329    0.013550
92648    0.013550
38778    0.013550
79837    0.013550
23860    0.013550
42049    0.013550
55065    0.013532
11768    0.013532
15377    0.013532
43076    0.013532
79906    0.013532
45860    0.013514
56138    0.013514
8830     0.013514
67020    0.012881
55606    0.012864
44307    0.012278
76445    0.012278
91711    0.012262
1535     0.012262
99746    0.012262
67529    0.012262
36344    0.012228
8350     0.012228
13752    0.012228
56321    0.012228
54229    0.012212
80005    0.012212
61477    0.012212
62661    0.012212
29661    0.012212
90014    0.012212
34953    0.012212
47470    0.012212
47863    0.012195
29436    0.012195
71832    0.012195
83869    0.012195
97377    0.012195
46946    0.012195
1612     0.012195
37302    0.012195
62935    0.012179
11413    0.012179
76631    0.012179
10280    0.012179
36541    0.011525
67038    0.010914
44857    0.010899
39211    0.010884
3452     0.010884
67216    0.010884
55428    0.010884
58275    0.010884
3905     0.010884
83252    0.010884
29105    0.010884
49879    0.010870
58259    0.010870
74555    0.010870
27358    0.010870
76240    0.010870
81649    0.010870
7764     0.010855
54418    0.010855
95842    0.010855
54726    0.010855
89084    0.010855
29032    0.010855
4364     0.010855
21087    0.010855
53926    0.010855
15010    0.010850
45896    0.010840
75238    0.010840
21790    0.010840
53803    0.010840
32044    0.010840
8324     0.010225
43903    0.010225
44265    0.010204
29127    0.010197
48636    0.010197
27837    0.010190
22046    0.010169
29081    0.009576
75490    0.009550
80021    0.009550
11769    0.009537
48706    0.009537
40336    0.009537
60963    0.009537
32784    0.009530
21090    0.009524
14522    0.009524
48214    0.009524
62023    0.009524
68961    0.009524
80138    0.009511
77379    0.009511
18917    0.009511
64017    0.009511
33404    0.009511
50469    0.009511
16037    0.009511
47515    0.009511
13361    0.009511
45415    0.009511
29324    0.009511
82936    0.009511
12992    0.009498
47032    0.009498
13484    0.008874
97375    0.008874
15486    0.008874
67545    0.008862
5486     0.008862
15727    0.008850
79237    0.008850
55771    0.008850
31567    0.008844
68723    0.008832
97033    0.008832
14707    0.008214
79772    0.008197
22311    0.008186
77338    0.008186
50527    0.008186
98304    0.008186
19154    0.008186
41812    0.008186
76951    0.008180
33873    0.008180
50312    0.008180
36009    0.008174
4286     0.008174
21658    0.008174
53186    0.008174
45808    0.008174
13469    0.008174
56379    0.008169
85253    0.008169
24266    0.008169
35581    0.008163
57717    0.008163
97210    0.008163
3220     0.008163
15665    0.008163
47110    0.008163
62075    0.008163
34668    0.008158
80824    0.008158
42731    0.008158
67635    0.008152
97383    0.008152
24983    0.007524
6441     0.007509
63565    0.007509
13755    0.007503
55403    0.007503
46290    0.007498
97476    0.007498
37165    0.007498
10970    0.007498
39157    0.007498
49826    0.007493
17929    0.007493
48043    0.007493
92882    0.007493
53120    0.007493
76008    0.007488
15056    0.007488
68463    0.007488
57036    0.007488
56729    0.007488
10504    0.007483
33417    0.007483
45331    0.007478
46143    0.007478
31632    0.007269
38677    0.007266
63829    0.006859
77971    0.006843
55388    0.006840
48206    0.006840
43767    0.006840
33844    0.006835
81005    0.006831
54654    0.006831
38315    0.006831
29809    0.006831
47987    0.006831
39825    0.006826
72341    0.006826
12093    0.006824
60072    0.006821
24927    0.006821
42634    0.006821
3753     0.006821
33809    0.006821
87540    0.006821
31547    0.006821
21913    0.006818
97452    0.006818
19007    0.006818
96135    0.006817
15480    0.006817
72959    0.006817
37040    0.006817
39439    0.006817
56548    0.006817
66020    0.006817
4616     0.006817
62926    0.006817
33981    0.006817
72529    0.006812
65354    0.006812
7005     0.006812
10548    0.006812
68626    0.006812
52217    0.006812
21619    0.006812
99783    0.006809
15923    0.006807
44483    0.006807
61560    0.006803
32442    0.006803
68638    0.006390
60913    0.006378
25049    0.006378
62067    0.006375
17060    0.006372
97441    0.006369
18433    0.006369
77026    0.006367
62424    0.006364
59542    0.006364
72583    0.006361
63867    0.006361
67556    0.006358
59710    0.006164
47838    0.006160
16329    0.006156
19310    0.006152
96727    0.006152
96103    0.006148
84325    0.006148
33813    0.006148
15834    0.006143
76443    0.006143
17327    0.006143
62888    0.006143
86018    0.006139
35803    0.006139
95148    0.006139
1330     0.006139
82711    0.006139
70003    0.006135
21208    0.006135
58015    0.006135
50664    0.006135
70466    0.006135
46723    0.006135
33909    0.006135
97132    0.006135
77417    0.006131
55001    0.006131
1545     0.006131
71854    0.006131
12222    0.006131
72059    0.006127
13367    0.005933
73027    0.005928
40914    0.005917
96038    0.005914
12466    0.005914
12455    0.005912
45307    0.005909
35554    0.005906
68932    0.005901
16034    0.005733
97403    0.005482
75236    0.005479
48221    0.005476
24340    0.005476
40202    0.005474
84003    0.005472
15829    0.005472
11957    0.005472
87313    0.005472
32960    0.005472
58769    0.005469
33620    0.005468
30803    0.005468
45698    0.005467
92210    0.005467
95537    0.005467
91206    0.005466
62673    0.005464
62939    0.005464
97753    0.005464
74047    0.005464
50535    0.005464
38039    0.005464
53924    0.005462
63131    0.005461
16878    0.005461
45342    0.005461
3816     0.005461
68859    0.005461
75980    0.005460
7022     0.005460
62360    0.005457
38079    0.005457
92561    0.005457
73134    0.005457
42273    0.005457
48202    0.005457
87543    0.005457
44702    0.005457
67851    0.005455
48371    0.005455
29860    0.005455
39840    0.005453
48850    0.005453
17051    0.005453
30257    0.005453
62970    0.005453
11978    0.005453
64686    0.005452
29209    0.005452
52563    0.005450
33956    0.005450
43070    0.005450
63336    0.005450
95528    0.005133
64470    0.005128
13615    0.005125
29939    0.005125
83120    0.005125
6782     0.005125
24070    0.005123
75703    0.005121
7439     0.005119
4047     0.005118
85086    0.005118
36758    0.005116
74633    0.005046
68641    0.005034
11964    0.005025
31771    0.005023
77358    0.005021
19456    0.005018
26339    0.005018
94015    0.005018
17850    0.005016
8014     0.005016
14586    0.005014
92637    0.005011
43760    0.005011
63453    0.005011
64058    0.005009
12410    0.005009
4074     0.005009
82063    0.005009
56152    0.005007
76566    0.005007
44902    0.005007
16421    0.005005
22151    0.005005
57732    0.005002
10962    0.005002
43330    0.004813
4210     0.004811
78113    0.004808
81642    0.004803
82221    0.004798
27311    0.004798
32935    0.004791
28372    0.004791
80736    0.004791
79063    0.004790
13342    0.004788
38060    0.004788
21524    0.004786
23303    0.004785
27249    0.004785
84002    0.004785
74074    0.004785
56546    0.004785
15557    0.004785
36111    0.004785
5654     0.004783
60193    0.004781
57426    0.004781
49705    0.004781
71291    0.004781
22824    0.004781
56068    0.004778
79539    0.004778
20776    0.004778
95567    0.004778
54896    0.004778
15077    0.004777
4555     0.004777
13316    0.004775
71762    0.004572
42211    0.004570
56549    0.004568
32780    0.004568
28901    0.004564
75661    0.004564
21102    0.004562
20012    0.004562
79085    0.004560
70062    0.004560
45801    0.004558
35901    0.004558
40170    0.004556
61530    0.004556
74130    0.004554
29061    0.004554
50073    0.004552
7980     0.004552
88355    0.004550
14510    0.004550
12460    0.004550
52572    0.004548
20036    0.004548
48088    0.004497
24433    0.004449
3601     0.004444
95453    0.004444
61830    0.004441
21865    0.004441
25442    0.004438
45150    0.004379
57374    0.004372
77566    0.004370
44412    0.004370
66618    0.004367
53153    0.004125
62262    0.004114
99033    0.004114
54154    0.004112
16858    0.004111
46366    0.004111
27522    0.004111
29320    0.004111
98665    0.004110
14425    0.004110
14037    0.004110
45106    0.004110
51453    0.004108
90403    0.004108
60432    0.004108
59014    0.004107
68973    0.004107
45879    0.004106
46322    0.004106
29817    0.004106
29911    0.004105
82514    0.004105
66070    0.004104
64076    0.004104
94619    0.004104
84532    0.004104
74536    0.004103
48034    0.004103
99113    0.004101
28423    0.004101
12910    0.004101
75452    0.004101
73669    0.004100
76834    0.004100
65680    0.004100
54981    0.004100
10604    0.004100
39897    0.004100
19017    0.004100
12575    0.004100
51521    0.004098
29170    0.004098
7640     0.004098
45051    0.004098
84735    0.004098
16114    0.004098
34135    0.004098
55080    0.004097
49621    0.004096
5155     0.004096
14120    0.004096
72513    0.004095
54559    0.004094
4226     0.004093
82901    0.003843
42171    0.003839
13647    0.003836
47451    0.003832
36617    0.003830
87558    0.003828
15449    0.003772
22810    0.003770
17041    0.003766
83643    0.003766
88325    0.003765
51006    0.003763
39665    0.003763
58579    0.003763
5084     0.003763
68881    0.003762
49632    0.003761
95629    0.003761
14733    0.003759
28654    0.003758
60091    0.003758
55128    0.003757
4287     0.003658
90250    0.003658
28117    0.003656
43160    0.003655
95827    0.003655
20634    0.003655
22213    0.003655
76248    0.003653
29819    0.003653
25106    0.003653
44223    0.003653
42701    0.003651
31305    0.003650
79548    0.003650
35903    0.003648
80951    0.003648
16362    0.003648
15686    0.003648
22853    0.003648
31042    0.003648
72476    0.003648
3818     0.003648
28611    0.003646
62571    0.003646
79252    0.003646
80436    0.003645
71232    0.003645
50421    0.003645
97813    0.003645
27807    0.003645
52576    0.003643
59871    0.003643
33510    0.003641
30009    0.003566
5733     0.003565
76665    0.003564
66941    0.003563
34112    0.003524
74875    0.003429
13425    0.003429
37663    0.003427
40077    0.003427
72047    0.003427
69165    0.003426
41056    0.003425
67232    0.003423
35776    0.003422
51632    0.003422
5461     0.003422
12419    0.003422
76366    0.003421
94971    0.003421
38740    0.003420
2630     0.003420
7711     0.003420
89512    0.003420
6444     0.003418
61454    0.003415
11217    0.003414
33967    0.003288
49440    0.003286
1843     0.003286
37932    0.003285
87533    0.003285
21750    0.003285
28314    0.003284
22968    0.003283
20895    0.003282
37849    0.003207
96776    0.003202
52535    0.003200
70056    0.003199
26292    0.003199
78040    0.003198
23850    0.003198
13811    0.003196
22015    0.003195
45622    0.003195
7060     0.003195
41254    0.003193
30756    0.003193
97034    0.003193
72042    0.003193
33872    0.003193
49613    0.003192
16239    0.003191
74131    0.003191
36507    0.003191
96037    0.003191
53129    0.003189
10039    0.003189
43102    0.003189
39769    0.003188
73754    0.003127
35747    0.003092
62856    0.003089
18103    0.003086
14778    0.003085
1844     0.003083
17088    0.003082
38922    0.003081
15324    0.003080
68950    0.003080
1257     0.003079
55046    0.003079
64114    0.003078
78631    0.003078
7750     0.003078
17058    0.003078
70531    0.003077
35811    0.003032
15920    0.003015
25213    0.003014
98027    0.003013
35229    0.003010
77327    0.003010
33040    0.003010
38761    0.002979
71960    0.002970
15484    0.002965
78584    0.002751
70726    0.002749
76578    0.002747
10463    0.002746
62668    0.002745
79759    0.002744
29455    0.002744
57756    0.002743
49775    0.002743
14711    0.002743
77412    0.002743
98233    0.002743
56592    0.002743
97014    0.002743
48174    0.002742
73564    0.002742
63010    0.002742
41810    0.002741
79842    0.002741
68031    0.002741
64659    0.002740
73034    0.002739
33710    0.002739
20687    0.002738
61272    0.002738
61335    0.002738
4680     0.002738
16314    0.002737
33470    0.002737
31563    0.002737
73559    0.002737
54441    0.002737
93627    0.002737
63665    0.002737
53801    0.002736
58651    0.002736
93529    0.002736
84540    0.002736
40820    0.002735
7208     0.002734
47434    0.002734
71277    0.002734
35764    0.002733
59448    0.002520
21872    0.002513
64019    0.002511
58569    0.002511
6024     0.002510
70774    0.002470
78214    0.002466
27258    0.002464
78248    0.002462
35049    0.002400
46765    0.002397
7747     0.002396
14816    0.002396
43321    0.002396
13304    0.002396
82501    0.002396
8323     0.002395
41836    0.002394
82227    0.002394
37754    0.002394
92128    0.002392
52768    0.002296
68403    0.002287
49895    0.002286
49628    0.002286
31046    0.002286
49259    0.002285
64630    0.002281
46346    0.002281
29438    0.002281
64726    0.002278
32323    0.002194
76626    0.002192
87035    0.002192
35022    0.002192
11796    0.002189
12534    0.002188
58531    0.002062
94558    0.002058
32725    0.002056
98238    0.002054
23937    0.001922
28659    0.001921
53061    0.001918
11710    0.001918
90650    0.001918
99323    0.001917
75048    0.001917
37132    0.001917
72011    0.001830
14537    0.001830
89319    0.001830
72165    0.001829
48438    0.001827
65072    0.001827
43985    0.001826
58765    0.001719
67584    0.001715
46702    0.001715
70732    0.001714
16048    0.001713
35651    0.001713
94569    0.001713
15432    0.001712
26041    0.001649
28073    0.001649
99160    0.001605
36749    0.001598
85173    0.001597
83646    0.001373
46254    0.001373
56019    0.001372
16839    0.001372
76678    0.001372
76857    0.001371
56668    0.001371
57340    0.001370
31605    0.001369
66018    0.001148
70808    0.001144
60958    0.001143
25526    0.001030
75662    0.000914
49854    0.000914
92585    0.000914
33811    0.000913
77007    0.000823
24970    0.000823
82072    0.000688
39073    0.000686
91321    0.000686
12986    0.000686
76050    0.000686
36869    0.000685
75092    0.000549
85020    0.000458
28405    0.000458
80120    0.000457
15217         NaN
19149         NaN
26237         NaN
31329         NaN
39113         NaN
40056         NaN
43408         NaN
44233         NaN
49101         NaN
51003         NaN
53228         NaN
54487         NaN
59714         NaN
63021         NaN
64874         NaN
72524         NaN
75218         NaN
75858         NaN
76905         NaN
79413         NaN
84087         NaN
87117         NaN
Name: zip, dtype: float64

**Curiously, a minority set of zip codes have a 1.0 correlation with fraud, while the remaining have at least an order of magnitude less correlation.**  
**We will later one-hot encode these into either the group with 1.0 correlation, or a group for the remaining lower correlations.**
**We will now examine *city*.**

In [13]:
pd.set_option('display.max_rows', None)  # or 1000
print((df.loc[df['is_fraud'] == 1, 'city'].value_counts() /\
       df['city'].value_counts()).sort_values(ascending=False))
pd.set_option('display.max_rows', 10)  # or 1000

Rice                         1.000000
Norfolk                      1.000000
Ridge Spring                 1.000000
East China                   1.000000
Queen Anne                   1.000000
Waukau                       1.000000
Pleasant Hill                1.000000
Freeport                     1.000000
Phelps                       1.000000
Beacon                       1.000000
Gaines                       1.000000
Granbury                     1.000000
Greenport                    1.000000
Grenola                      1.000000
Brookfield                   1.000000
Guthrie                      1.000000
Orange Park                  1.000000
Oakton                       1.000000
North East                   1.000000
Downey                       1.000000
Wartburg                     1.000000
Wappapello                   1.000000
Springville                  1.000000
Buellton                     1.000000
Byesville                    1.000000
Vacaville                    1.000000
Chattanooga                  1.000000
Streator                     1.000000
Clarion                      1.000000
Claypool                     1.000000
Clinton                      1.000000
Walkertown                   1.000000
Coulee Dam                   1.000000
Craig                        1.000000
Senatobia                    1.000000
Seligman                     1.000000
Seattle                      1.000000
Crouse                       1.000000
Roland                       1.000000
West Frankfort               1.000000
Grifton                      1.000000
Morven                       1.000000
Kirtland                     1.000000
Noblesville                  1.000000
Morrowville                  1.000000
Kaktovik                     1.000000
Karns City                   1.000000
Winnsboro                    1.000000
Mineral                      1.000000
Kirkwood                     1.000000
La Grande                    1.000000
Moss Point                   1.000000
Melville                     1.000000
Medford                      1.000000
Marshall                     1.000000
Las Vegas                    1.000000
Madisonville                 1.000000
Lexington                    1.000000
Lockhart                     1.000000
Angwin                       1.000000
Bruce                        1.000000
Mount Vernon                 1.000000
Irvington                    1.000000
Nicholson                    1.000000
Ashland                      1.000000
Hubbell                      1.000000
Nanuet                       1.000000
Mountain City                1.000000
Wever                        1.000000
Isanti                       1.000000
Clearwater                   0.031873
Aurora                       0.030667
Benton                       0.026667
Jay                          0.021534
Chatham                      0.021534
Moscow                       0.021477
Riverview                    0.020243
Boulder                      0.020188
Girard                       0.020188
Whittemore                   0.020188
Howes Cave                   0.020188
White Sulphur Springs        0.020161
Pearlington                  0.020161
Providence                   0.020134
Monitor                      0.018919
Moriches                     0.018893
Old Hickory                  0.018868
Rock Glen                    0.018868
Mc Clellandtown              0.018868
Saint Francis                0.018868
Preston                      0.018868
Burns Flat                   0.018843
Sardis                       0.018843
New Memphis                  0.018817
Elk Rapids                   0.018817
Achille                      0.017568
Du Pont                      0.017544
Brashear                     0.017544
Owensville                   0.017544
Williamsburg                 0.017520
Ironton                      0.017497
Newport                      0.017497
Sprague                      0.017497
Skytop                       0.016327
Wittenberg                   0.016327
Ragland                      0.016304
Daniels                      0.016260
Adams                        0.016238
Webster City                 0.016238
Prairie Creek                0.016238
Livonia                      0.016238
Albuquerque                  0.016227
Lorenzo                      0.016216
Ferney                       0.016216
Gaithersburg                 0.016216
Dadeville                    0.016216
Etlan                        0.016216
Bigelow                      0.016216
Westfir                      0.016194
Vienna                       0.016194
Valentine                    0.016194
Washoe Valley                0.016194
Annapolis                    0.016173
Yellowstone National Park    0.016173
Paris                        0.016173
Emmons                       0.016173
Damascus                     0.014946
Loving                       0.014925
Jordan Valley                0.014925
Mc Intosh                    0.014925
Stoneham                     0.014905
Sea Island                   0.014905
Knowlesville                 0.014885
Remer                        0.014885
Azusa                        0.014885
Bay City                     0.014885
Louisiana                    0.014885
Fairhope                     0.014885
Manquin                      0.014865
South Richmond Hill          0.014865
Ravenna                      0.014865
Lithopolis                   0.014865
Palmdale                     0.014865
Greenbush                    0.013624
Lepanto                      0.013605
North Haverhill              0.013587
Parker Dam                   0.013587
East Rochester               0.013569
Newton                       0.013569
Pea Ridge                    0.013569
Wendel                       0.013569
Hopewell                     0.013550
Huntington Beach             0.013550
Amorita                      0.013550
Premier                      0.013550
Hazel                        0.013550
Omaha                        0.013550
Sunflower                    0.013550
Dell City                    0.013550
Humboldt                     0.013550
Thornville                   0.013532
West Finley                  0.013532
Northport                    0.013532
El Paso                      0.013532
Albany                       0.013523
Maria Stein                  0.013514
Iselin                       0.013514
Hills                        0.013514
Hampton                      0.013514
Burrton                      0.012881
Hovland                      0.012864
Akron                        0.012278
Desdemona                    0.012278
Claremont                    0.012262
Garfield                     0.012262
North Brookfield             0.012262
Huslia                       0.012262
Richland                     0.012228
Collegeville                 0.012228
Hartford                     0.012228
De Lancey                    0.012228
Los Angeles                  0.012212
Williams                     0.012212
Smithfield                   0.012212
Port Saint Lucie             0.012212
Marietta                     0.012212
Loami                        0.012212
New Franken                  0.012212
Arvada                       0.012212
De Queen                     0.012195
Paxton                       0.012195
Liberty Mills                0.012195
Apison                       0.012195
Cross                        0.012195
Shedd                        0.012195
New Goshen                   0.012195
Spirit Lake                  0.012195
Galatia                      0.012179
Springfield Gardens          0.012179
Bynum                        0.012179
Grand Bay                    0.011525
Randolph                     0.011317
Dexter                       0.010914
Monetta                      0.010884
Jackson                      0.010884
Reynolds                     0.010884
Kittery Point                0.010884
Jaffrey                      0.010884
Malad City                   0.010884
Republic                     0.010870
Red Cliff                    0.010870
Gainesville                  0.010870
Lane                         0.010870
Michigan                     0.010870
Boyd                         0.010855
Dalton                       0.010855
Kingsville                   0.010855
Cassatt                      0.010855
West Long Branch             0.010855
North Las Vegas              0.010855
Bryant                       0.010855
Winthrop                     0.010855
Beaver Falls                 0.010850
Waynesfield                  0.010840
Tuscarora                    0.010840
Des Moines                   0.010421
Heislerville                 0.010225
Amsterdam                    0.010225
Luzerne                      0.010197
Prosperity                   0.010197
Grimesland                   0.010190
Falls Church                 0.010169
Ehrhardt                     0.009576
Broomfield                   0.009550
Trenton                      0.009550
Oakdale                      0.009537
Rossville                    0.009537
Umatilla                     0.009530
Nelson                       0.009524
Eagarville                   0.009524
Linthicum Heights            0.009524
Palmyra                      0.009524
Parker                       0.009511
Jordanville                  0.009511
Harmony                      0.009511
New York City                0.009511
Lonetree                     0.009511
Spring                       0.009511
Dayton                       0.009511
Dublin                       0.009511
Rockwell                     0.009511
Bristow                      0.009511
Clifton                      0.009511
Moores Hill                  0.009498
West Chazy                   0.009498
Camden                       0.009244
Arlington                    0.009087
Kenner                       0.009079
West Eaton                   0.008874
Vanderbilt                   0.008874
Scotts Mills                 0.008874
South Hero                   0.008862
Orr                          0.008850
Hedley                       0.008850
Clune                        0.008850
West Green                   0.008844
Carroll                      0.008832
Kent                         0.008832
Minneapolis                  0.008632
Pecos                        0.008197
Ashford                      0.008186
Humble                       0.008186
Curlew                       0.008186
Deane                        0.008186
Alexandria                   0.008186
Sterling City                0.008180
Wauchula                     0.008180
Waukesha                     0.008174
West Bethel                  0.008174
Beaverdam                    0.008174
Brantley                     0.008174
Queenstown                   0.008174
Stittville                   0.008174
Sauk Rapids                  0.008169
Paradise Valley              0.008169
Lebanon                      0.008169
Nokomis                      0.008163
Belle Fourche                0.008163
Belmont                      0.008163
Portland                     0.008163
Central                      0.008163
Manor                        0.008163
Phil Campbell                0.008163
West Palm Beach              0.008160
Kirk                         0.008158
Port Richey                  0.008158
Dubre                        0.008158
Stayton                      0.008152
Dresden                      0.008152
Louisville                   0.007842
Georgetown                   0.007836
Dallas                       0.007586
Union                        0.007524
Higganum                     0.007509
Unionville                   0.007509
Downsville                   0.007503
Slayden                      0.007498
Pomona                       0.007498
Ridgeland                    0.007498
Sixes                        0.007498
Cressona                     0.007493
Rumely                       0.007493
East Troy                    0.007493
Mount Clemens                0.007493
Corona                       0.007493
Weeping Water                0.007488
Leetsdale                    0.007488
Aledo                        0.007488
Halma                        0.007488
Hurley                       0.007488
Armonk                       0.007483
Greenwood                    0.007478
Greenville                   0.007478
Irvine                       0.007286
Hahira                       0.007269
University                   0.007266
Cardwell                     0.006859
Lolita                       0.006843
Norwich                      0.006840
Watertown                    0.006840
Haines City                  0.006835
New Ellenton                 0.006831
Seneca                       0.006831
Veedersburg                  0.006831
Pueblo                       0.006831
Bethel Springs               0.006831
Haynes                       0.006826
Brinson                      0.006826
Mesa                         0.006826
Jefferson                    0.006824
Ringwood                     0.006821
Kings Bay                    0.006821
Parkers Lake                 0.006821
Grantham                     0.006821
Cass                         0.006821
Lamy                         0.006821
Cecilton                     0.006818
Lowell                       0.006818
Bristol                      0.006818
Heidelberg                   0.006817
Halstad                      0.006817
Dongola                      0.006817
Easton                       0.006817
Smock                        0.006817
Winslow                      0.006817
Brooklin                     0.006817
Port Charlotte               0.006817
Vinton                       0.006817
Chester                      0.006812
Cherokee Village             0.006812
Brainard                     0.006812
Boonton                      0.006812
Syracuse                     0.006812
Clutier                      0.006812
Montrose                     0.006812
Wales                        0.006809
Bolivar                      0.006807
Grand Ridge                  0.006803
Putnam                       0.006803
Houston                      0.006650
Allentown                    0.006642
Detroit                      0.006440
Fullerton                    0.006390
Comfort                      0.006378
Bonfield                     0.006378
Moro                         0.006375
Mill Creek                   0.006372
Gardiner                     0.006369
Jermyn                       0.006369
Dieterich                    0.006364
Turner                       0.006364
Viola                        0.006361
Clarksville                  0.006361
Matthews                     0.006361
Mc Cracken                   0.006358
Alder                        0.006164
Carlisle                     0.006160
Honokaa                      0.006152
Atglen                       0.006152
Mendon                       0.006148
Blairsden-Graeagle           0.006148
Summerfield                  0.006145
Emporium                     0.006143
Glen Rock                    0.006143
Tamaroa                      0.006143
Cross Plains                 0.006143
San Jose                     0.006139
Ashfield                     0.006139
Alva                         0.006139
Parks                        0.006139
Tulsa                        0.006136
Oran                         0.006135
Christine                    0.006135
Tickfaw                      0.006135
Newberg                      0.006135
Cape Coral                   0.006135
Pikesville                   0.006135
Metairie                     0.006135
Topeka                       0.006135
Churubusco                   0.006135
Beasley                      0.006131
Texarkana                    0.006131
Shrewsbury                   0.006131
Gregory                      0.006127
Washington                   0.006043
Lowville                     0.005933
Coyle                        0.005928
Big Creek                    0.005917
Port Ewen                    0.005914
Grenada                      0.005914
Margaretville                0.005912
Bowersville                  0.005909
Eldridge                     0.005906
Campbell                     0.005901
Fenelton                     0.005733
Huntsville                   0.005683
Eugene                       0.005482
Glade Spring                 0.005476
Crownpoint                   0.005472
Vero Beach                   0.005472
Corsica                      0.005472
American Fork                0.005472
Palermo                      0.005469
Avera                        0.005468
Sacramento                   0.005468
Tampa                        0.005468
Indian Wells                 0.005467
Fields Landing               0.005467
Zaleski                      0.005467
Glendale                     0.005466
Oakford                      0.005464
Powell Butte                 0.005464
Early                        0.005464
Grand Junction               0.005464
Goreville                    0.005464
Mounds                       0.005464
Cazenovia                    0.005462
Meadville                    0.005461
Saint Louis                  0.005461
West Decatur                 0.005461
Miamisburg                   0.005461
Center Tuftonboro            0.005461
North Loup                   0.005461
Zavalla                      0.005460
Fairview                     0.005460
Mountain Center              0.005457
Llano                        0.005457
Payson                       0.005457
Tiptonville                  0.005457
Canton                       0.005457
Rochester                    0.005457
Afton                        0.005457
Oklahoma City                0.005457
Holcomb                      0.005455
Oxford                       0.005455
North Augusta                0.005455
Mc Veytown                   0.005453
Lakeview                     0.005453
Cuthbert                     0.005453
Westhampton Beach            0.005453
Milner                       0.005453
Olmsted                      0.005453
Columbia                     0.005452
Hedrick                      0.005450
Saint James City             0.005450
Rosewood                     0.005450
Carlotta                     0.005133
Arcadia                      0.005128
Mound City                   0.005128
Scotia                       0.005125
Freedom                      0.005125
Plymouth                     0.005125
Brownville                   0.005125
Catawba                      0.005123
Tyler                        0.005121
Ogdensburg                   0.005119
Parsonsfield                 0.005118
Plantersville                0.005116
Howells                      0.005034
Shelter Island               0.005025
Norman Park                  0.005023
New Waverly                  0.005021
Daly City                    0.005018
Center Point                 0.005018
Oaks                         0.005018
Montandon                    0.005016
Bridgeport                   0.005016
West Henrietta               0.005014
Warren                       0.005012
Laguna Hills                 0.005011
Mount Perry                  0.005011
Luray                        0.005011
Scarborough                  0.005009
Independence                 0.005009
Jelm                         0.005009
Big Indian                   0.005009
Mansfield                    0.005007
Purmela                      0.005007
Lamberton                    0.005007
Harborcreek                  0.005005
Orangeburg                   0.005002
Deadwood                     0.005002
Naples                       0.004958
Wichita                      0.004923
San Diego                    0.004913
Kirby                        0.004813
Auburn                       0.004811
Falls City                   0.004808
Meredith                     0.004803
Lagrange                     0.004798
Pelham                       0.004798
Pembroke                     0.004791
Iliff                        0.004791
Melbourne                    0.004791
Nazareth                     0.004790
Garrattsville                0.004788

**This has the same correlation pattern as zip:fraud.**  
**We will later one-hot-encode these.**  
**Now we will examine state.**

In [14]:
pd.set_option('display.max_rows', None)  # or 1000
print((df.loc[df['is_fraud'] == 1, 'state'].value_counts() /\
       df['state'].value_counts()).sort_values(ascending=False))
pd.set_option('display.max_rows', 10)  # or 1000

DE    1.000000
RI    0.020134
AK    0.016875
OR    0.007460
NH    0.006737
VA    0.006538
TN    0.006382
NE    0.006275
MN    0.006163
NY    0.006113
DC    0.006043
KS    0.005859
NV    0.005833
CO    0.005818
ME    0.005718
SC    0.005655
MS    0.005629
FL    0.005496
IN    0.005488
GA    0.005463
WI    0.005463
IA    0.005438
MD    0.005436
KY    0.005417
OH    0.005403
OK    0.005256
SD    0.005235
IL    0.005208
NM    0.005165
CT    0.005101
PA    0.005010
CA    0.004994
MA    0.004954
MO    0.004772
AL    0.004750
WA    0.004660
NJ    0.004583
MI    0.004542
NC    0.004521
HI    0.004385
TX    0.004376
AR    0.004371
WY    0.004284
VT    0.004283
AZ    0.004166
ID    0.004107
MT    0.004106
WV    0.003997
UT    0.003972
ND    0.003965
LA    0.003773
Name: state, dtype: float64

**This has the same correlation pattern as zip:fraud, but narrowed down to a single state.**  
**We will one-hot-encode this.**  
**Now we will examine *job*.**

In [15]:
pd.set_option('display.max_rows', None)  # or 1000
print((df.loc[df['is_fraud'] == 1, 'job'].value_counts() /\
       df['job'].value_counts()).sort_values(ascending=False))
pd.set_option('display.max_rows', 10)  # or 1000

Homeopath                                                      1.000000
Accountant, chartered                                          1.000000
Forest/woodland manager                                        1.000000
Software engineer                                              1.000000
Ship broker                                                    1.000000
Armed forces technical officer                                 1.000000
Dancer                                                         1.000000
Sales promotion account executive                              1.000000
Air traffic controller                                         1.000000
Broadcast journalist                                           1.000000
Contracting civil engineer                                     1.000000
Industrial buyer                                               1.000000
Information officer                                            1.000000
Engineer, water                                                1.000000
Engineer, site                                                 1.000000
Careers adviser                                                1.000000
Personnel officer                                              1.000000
Veterinary surgeon                                             1.000000
Operational investment banker                                  1.000000
Legal secretary                                                1.000000
Warehouse manager                                              1.000000
Solicitor                                                      1.000000
TEFL teacher                                                   0.042105
Lawyer                                                         0.036988
Community development worker                                   0.029294
Accountant, chartered certified                                0.027963
Horticultural consultant                                       0.025469
Clinical cytogeneticist                                        0.024194
Nature conservation officer                                    0.021534
Geneticist, molecular                                          0.021477
Writer                                                         0.020243
Conservator, museum/gallery                                    0.020188
Magazine journalist                                            0.018817
Field trials officer                                           0.017568
Medical technical officer                                      0.016880
Civil Service administrator                                    0.016238
Jewellery designer                                             0.016227
Minerals surveyor                                              0.016216
Charity officer                                                0.016216
Pharmacist, hospital                                           0.016183
Television camera operator                                     0.016173
Economist                                                      0.015572
Engineer, structural                                           0.014905
Artist                                                         0.014905
Solicitor, Scotland                                            0.014865
Interior and spatial designer                                  0.014865
Engineer, building services                                    0.014865
Chief of Staff                                                 0.013596
Marketing executive                                            0.013587
Teacher, adult education                                       0.013569
Advertising account executive                                  0.013556
Education officer, community                                   0.013550
Purchasing manager                                             0.013550
Hydrogeologist                                                 0.013550
Air cabin crew                                                 0.013532
Tour manager                                                   0.013532
Designer, television/film set                                  0.013514
Data scientist                                                 0.013514
Set designer                                                   0.013134
Biochemist, clinical                                           0.012908
Civil Service fast streamer                                    0.012873
Engineer, civil (consulting)                                   0.012262
Research scientist (medical)                                   0.012245
English as a foreign language teacher                          0.012212
Primary school teacher                                         0.012212
Hotel manager                                                  0.012212
Occupational therapist                                         0.012195
Restaurant manager, fast food                                  0.012179
Optometrist                                                    0.011754
Retail manager                                                 0.011565
Higher education careers adviser                               0.011312
Copy                                                           0.010899
Commissioning editor                                           0.010899
Visual merchandiser                                            0.010884
Broadcast engineer                                             0.010884
Textile designer                                               0.010884
Analytical chemist                                             0.010884
Surveyor, hydrographic                                         0.010884
Engineer, manufacturing                                        0.010870
Producer, television/film/video                                0.010870
Designer, multimedia                                           0.010862
Nurse, children's                                              0.010858
Presenter, broadcasting                                        0.010855
Catering manager                                               0.010855
Network engineer                                               0.010850
Public relations officer                                       0.010840
Production assistant, television                               0.010840
Oncologist                                                     0.010840
Human resources officer                                        0.010612
Manufacturing systems engineer                                 0.010190
Sales executive                                                0.009973
Colour technologist                                            0.009911
Senior tax professional/tax inspector                          0.009699
Engineer, materials                                            0.009576
Investment banker, operational                                 0.009550
Water quality scientist                                        0.009537
Buyer, retail                                                  0.009537
Conservator, furniture                                         0.009524
Aeronautical engineer                                          0.009511
Environmental manager                                          0.009511
Administrator, arts                                            0.009511
Horticultural therapist                                        0.009181
Politician's assistant                                         0.009171
Medical secretary                                              0.008862
Architect                                                      0.008856
Museum/gallery conservator                                     0.008844
Museum education officer                                       0.008832
Wellsite geologist                                             0.008722
Theatre director                                               0.008625
Quantity surveyor                                              0.008540
Trading standards officer                                      0.008471
Administrator, local government                                0.008431
Merchandiser, retail                                           0.008197
Designer, interior/spatial                                     0.008189
Conservation officer, historic buildings                       0.008186
Estate manager/land agent                                      0.008186
Transport planner                                              0.008177
Therapist, music                                               0.008171
Armed forces training and education officer                    0.008170
Hydrographic surveyor                                          0.008169
Teacher, English as a foreign language                         0.008169
Hospital pharmacist                                            0.008163
Community pharmacist                                           0.008163
Engineer, aeronautical                                         0.008163
Scientist, research (medical)                                  0.008163
Therapist, horticultural                                       0.008161
Sport and exercise psychologist                                0.008160
Environmental education officer                                0.008158
Emergency planning/management officer                          0.008156
Hydrologist                                                    0.008156
Private music teacher                                          0.008009
Exercise physiologist                                          0.007989
Broadcast presenter                                            0.007972
Bookseller                                                     0.007898
Fitness centre manager                                         0.007898
Geochemist                                                     0.007887
Clinical biochemist                                            0.007853
Theme park manager                                             0.007850
Chief Marketing Officer                                        0.007842
Glass blower/designer                                          0.007823
Field seismologist                                             0.007724
Chartered accountant                                           0.007713
Archaeologist                                                  0.007509
Scientist, biomedical                                          0.007506
Scientist, clinical (histocompatibility and immunogenetics)    0.007498
General practice doctor                                        0.007498
Academic librarian                                             0.007498
Education officer, museum                                      0.007493
Ecologist                                                      0.007493
Landscape architect                                            0.007493
Communications engineer                                        0.007480
Media planner                                                  0.007478
Tree surgeon                                                   0.007268
Armed forces logistics/support/administrative officer          0.007263
Embryologist, clinical                                         0.007263
Research officer, trade union                                  0.007207
Scientist, physiological                                       0.007177
Psychiatrist                                                   0.007167
Further education lecturer                                     0.007161
Public affairs consultant                                      0.007155
Psychologist, sport and exercise                               0.007153
Animal nutritionist                                            0.007143
Chief Technology Officer                                       0.007088
Administrator, education                                       0.007081
Freight forwarder                                              0.007050
Lecturer, higher education                                     0.007039
Forensic psychologist                                          0.007022
Buyer, industrial                                              0.007000
Editor, film/video                                             0.006831
Retail buyer                                                   0.006831
Teaching laboratory technician                                 0.006827
Police officer                                                 0.006827
Hospital doctor                                                0.006827
Programmer, applications                                       0.006826
Engineer, broadcasting (operations)                            0.006826
Diagnostic radiographer                                        0.006824
Special effects artist                                         0.006821
Plant breeder/geneticist                                       0.006821
Outdoor activities/education manager                           0.006821
Charity fundraiser                                             0.006819
Loss adjuster, chartered                                       0.006817
Barrister's clerk                                              0.006817
Air broker                                                     0.006817
Furniture designer                                             0.006817
Pathologist                                                    0.006817
Education administrator                                        0.006817
Soil scientist                                                 0.006814
Development worker, international aid                          0.006814
Pharmacologist                                                 0.006812
Associate Professor                                            0.006812
Art gallery manager                                            0.006803
Systems analyst                                                0.006625
Licensed conveyancer                                           0.006597
Occupational hygienist                                         0.006591
Audiological scientist                                         0.006590
Maintenance engineer                                           0.006556
Equality and diversity officer                                 0.006554
Civil engineer, contracting                                    0.006487
Investment banker, corporate                                   0.006485
Chiropodist                                                    0.006433
Science writer                                                 0.006410
Surveyor, mining                                               0.006390
Gaffer                                                         0.006371
Therapist, occupational                                        0.006369
Training and development officer                               0.006369
Engineer, maintenance                                          0.006369
Animator                                                       0.006367
Commercial horticulturist                                      0.006365
Psychologist, clinical                                         0.006364
Psychiatric nurse                                              0.006361
Television/film/video producer                                 0.006302
Engineer, petroleum                                            0.006288
Mental health nurse                                            0.006281
Building control surveyor                                      0.006267
Curator                                                        0.006153
Product manager                                                0.006152
Chartered legal executive (England and Wales)                  0.006148
Insurance claims handler                                       0.006143
Production assistant, radio                                    0.006139
Chemical engineer                                              0.006136
Neurosurgeon                                                   0.006135
Company secretary                                              0.006135
Sports administrator                                           0.006135
Designer, textile                                              0.006131
Mechanical engineer                                            0.006078
Teacher, early years/pre                                       0.006008
Chief Financial Officer                                        0.006006
Prison officer                                                 0.005960
Producer, radio                                                0.005917
Environmental health practitioner                              0.005912
Insurance risk surveyor                                        0.005845
Art therapist                                                  0.005810
Museum/gallery exhibitions officer                             0.005802
Information systems manager                                    0.005796
Race relations officer                                         0.005772
Television production assistant                                0.005756
Database administrator                                         0.005742
Product designer                                               0.005736
Phytotherapist                                                 0.005696
Podiatrist                                                     0.005669
Designer, industrial/product                                   0.005635
Futures trader                                                 0.005631
Industrial/product designer                                    0.005479
Clinical psychologist                                          0.005476
IT consultant                                                  0.005472
Tax adviser                                                    0.005467
Learning mentor                                                0.005467
Local government officer                                       0.005464
Administrator, charities/voluntary organisations               0.005461
Patent attorney                                                0.005461
Farm manager                                                   0.005459
Engineer, biomedical                                           0.005457
Advertising copywriter                                         0.005457
Scientific laboratory technician                               0.005457
Architectural technologist                                     0.005457
Risk analyst                                                   0.005457
Metallurgist                                                   0.005457
Nutritional therapist                                          0.005453
Professor Emeritus                                             0.005450
Historic buildings inspector/conservation officer              0.005349
Financial trader                                               0.005339
Research scientist (physical sciences)                         0.005329
Counselling psychologist                                       0.005311
Naval architect                                                0.005308
Materials engineer                                             0.005294
Probation officer                                              0.005294
Engineering geologist                                          0.005293
Engineer, mining                                               0.005282
Video editor                                                   0.005244
Geologist, engineering                                         0.005237
Arboriculturist                                                0.005232
Land/geomatics surveyor                                        0.005216
Market researcher                                              0.005194
Editor, magazine features                                      0.005135
Pilot, airline                                                 0.005127
Development worker, community                                  0.005126
Herpetologist                                                  0.005125

**The same pattern emerges here.**  
**We will later one-hot-encode the jobs with 1.0 correlation against a group comprised of the lower correlations.**  
  
**We now convert *dob* to pandas datetime objects and examine.**

In [16]:
df['dob'] = pd.to_datetime(df['dob'])
print(df['dob'])

0         1988-03-09
1         1978-06-21
2         1962-01-19
3         1967-01-12
4         1986-03-28
             ...
1852389   1966-02-13
1852390   1999-12-27
1852391   1981-11-29
1852392   1965-12-15
1852393   1993-05-10
Name: dob, Length: 1852394, dtype: datetime64[ns]

**We will later extract the year into its own feature, and encode month/day to preserve its cyclical nature.**

**We will later drop *trans_num* and *unix_time*.**  
***trans_num* is unique per data point, and date/time will be better captured by the re-coding of *trans_date_trans_time* in the next section.**

## Clean up
* Find and List number of blank entries and outliers/errors
* Take corrective actions and provide justification
* Remove unnecessary features
* If a categorical approach breakout the input features (X) from the output features (y)

**In the previous section we discussed the need to re-code date/time to preserve the ordering of year, and also the cyclical nature of days within a year as well as seconds within a day.**  
**We convert *trans_date_trans_time* to pandas datetime objects to allow easier separation of calendar day and time.**

In [17]:
print(type(df['trans_date_trans_time'][0]))
print(df['trans_date_trans_time'][0])

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
2019-01-01 00:00:18

**Now create a year column**

In [18]:
df['year'] = df['trans_date_trans_time'].dt.year
print(df['year'])

0          2019
1          2019
2          2019
3          2019
4          2019
           ...
1852389    2020
1852390    2020
1852391    2020
1852392    2020
1852393    2020
Name: year, Length: 1852394, dtype: int64

**Now create a day of year column**  
**This is used for sine/cosine facetization, and will later be dropped.**

In [19]:
df['day_of_year'] = df['trans_date_trans_time'].dt.day_of_year
print(df['day_of_year'])

0            1
1            1
2            1
3            1
4            1
          ...
1852389    366
1852390    366
1852391    366
1852392    366
1852393    366
Name: day_of_year, Length: 1852394, dtype: int64

**Now create a seconds in day column**  
**This is used for sine/cosine facetization, and will later be dropped.**

In [20]:
df['sec_of_day'] = df['trans_date_trans_time'].dt.second +\
        60 * df['trans_date_trans_time'].dt.minute +\
        3600 * df['trans_date_trans_time'].dt.hour
print(df['sec_of_day'])

0             18
1             44
2             51
3             76
4            186
           ...
1852389    86347
1852390    86349
1852391    86355
1852392    86364
1852393    86374
Name: sec_of_day, Length: 1852394, dtype: int64

**Now we can expand both *day_of_year* and *sec_of_day* out to sine and cosine facets, in order to preserve their cyclical nature.**

In [21]:
# First do day_of_year
df['doy_x'] =\
        np.cos(2 * np.pi * df.loc[df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        366)  # x component of day_of_year for leap years
df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'doy_x'] =\
        np.cos(2 * np.pi * df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        365)  # x component of day_of_year for non leap years
df['doy_y'] =\
        np.sin(2 * np.pi * df.loc[df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        366)  # y component of day_of_year for leap years
df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'doy_y'] =\
        np.sin(2 * np.pi * df.loc[~df['trans_date_trans_time'].dt.is_leap_year, 'day_of_year'] /\
        365)  # y component of day_of_year for non leap years

# Now do sec_of_day
df['sod_x'] = np.cos(2 * np.pi * df['sec_of_day'] / 86400)  # x component of sec_of_day
df['sod_y'] = np.sin(2 * np.pi * df['sec_of_day'] / 86400)  # x component of sec_of_day

print(df['doy_x'])
print(df['doy_y'])
print(df['sod_x'])
print(df['sod_y'])

0          0.999852
1          0.999852
2          0.999852
3          0.999852
4          0.999852
             ...
1852389    1.000000
1852390    1.000000
1852391    1.000000
1852392    1.000000
1852393    1.000000
Name: doy_x, Length: 1852394, dtype: float64
0          1.721336e-02
1          1.721336e-02
2          1.721336e-02
3          1.721336e-02
4          1.721336e-02
               ...
1852389   -2.449294e-16
1852390   -2.449294e-16
1852391   -2.449294e-16
1852392   -2.449294e-16
1852393   -2.449294e-16
Name: doy_y, Length: 1852394, dtype: float64
0          0.999999
1          0.999995
2          0.999993
3          0.999985
4          0.999909
             ...
1852389    0.999993
1852390    0.999993
1852391    0.999995
1852392    0.999997
1852393    0.999998
Name: sod_x, Length: 1852394, dtype: float64
0          0.001309
1          0.003200
2          0.003709
3          0.005527
4          0.013526
             ...
1852389   -0.003854
1852390   -0.003709
1852391   -0.003272
1852392   -0.002618
1852393   -0.001891
Name: sod_y, Length: 1852394, dtype: float64

**Now we can drop *trans_date_trans_time* as well as the temporarily created columns.**

In [22]:
df = df.drop(columns=['trans_date_trans_time', 'day_of_year', 'sec_of_day'])

**Now drop *cc_num*, *merchant*, *first*, *last*, and *street*, according to the discussion in the previous section.**

In [23]:
df = df.drop(columns=['cc_num', 'merchant', 'first', 'last', 'street'])

**Now one-hot-encode *category*, *sex*, *zip*, *city*, *state*, and *job* for the reasons discussed in the previous section.**

In [24]:
df = pd.get_dummies(data=df, columns=['category', 'sex'])

***category* and *sex* are done, now move on to *zip*, *city*, *state*, and *job*.**

***zip* is done, now repeat the process for *city*, *state*, and *job*.**

In [25]:
def ohe(df, params):
    for param in params:
        df['{}_cor'.format(param)] = 0
        valscounts = (df.loc[df['is_fraud'] == 1, '{}'.format(param)].value_counts() /\
               df['{}'.format(param)].value_counts()).sort_values(ascending=False) == 1.0
        truevals = []
        for zc, bval in valscounts.items():
            if bval == True:
                truevals.append(zc)

        df.loc[df['{}'.format(param)].isin(truevals), '{}_cor'.format(param)] = 1
        print(df['{}_cor'.format(param)].value_counts())
        df = pd.get_dummies(data=df, columns=['{}_cor'.format(param)])
        df = df.drop(columns=['{}'.format(param)])

    return df
        
df = ohe(df, ['zip', 'city', 'state', 'job'])

0    1851517
1        877
Name: zip_cor, dtype: int64
0    1851685
1        709
Name: city_cor, dtype: int64
0    1852385
1          9
Name: state_cor, dtype: int64
0    1852157
1        237
Name: job_cor, dtype: int64

**Now re-code *dob* as discussed above.**

In [26]:
df['dob_year'] = df['dob'].dt.year
print(df['dob_year'])

0          1988
1          1978
2          1962
3          1967
4          1986
           ...
1852389    1966
1852390    1999
1852391    1981
1852392    1965
1852393    1993
Name: dob_year, Length: 1852394, dtype: int64

In [27]:
# create a temporary column for the day of year for the date of birth
# this will be deleted after sine/cosine facetization
df['dob_doy'] = df['dob'].dt.day_of_year
print(df['dob_doy'])

0           69
1          172
2           19
3           12
4           87
          ...
1852389     44
1852390    361
1852391    333
1852392    349
1852393    130
Name: dob_doy, Length: 1852394, dtype: int64

In [28]:
# now sine/cosine facetize
df['dob_doy_x'] =\
        np.cos(2 * np.pi * df.loc[df['dob'].dt.is_leap_year, 'dob_doy'] /\
        366)  # x component of day_of_year for leap years
df.loc[~df['dob'].dt.is_leap_year, 'dob_doy_x'] =\
        np.cos(2 * np.pi * df.loc[~df['dob'].dt.is_leap_year, 'dob_doy'] /\
        365)  # x component of day_of_year for non leap years
df['dob_doy_y'] =\
        np.sin(2 * np.pi * df.loc[df['dob'].dt.is_leap_year, 'dob_doy'] /\
        366)  # y component of day_of_year for leap years
df.loc[~df['dob'].dt.is_leap_year, 'dob_doy_y'] =\
        np.sin(2 * np.pi * df.loc[~df['dob'].dt.is_leap_year, 'dob_doy'] /\
        365)  # y component of day_of_year for non leap years

In [29]:
df = df.drop(columns=['dob', 'dob_doy'])

**Now drop *trans_num* and *unix_time* as discussed above*.**

In [30]:
df = df.drop(columns=['trans_num', 'unix_time'])

**Now check the cleaned dataframe**

In [31]:
df

,amt,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,doy_x,doy_y,sod_x,sod_y,category_entertainment,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,sex_F,sex_M,zip_cor_0,zip_cor_1,city_cor_0,city_cor_1,state_cor_0,state_cor_1,job_cor_0,job_cor_1,dob_year,dob_doy_x,dob_doy_y
0,4.97,36.0788,-81.1781,3495,36.011293,-82.048315,0,2019,0.999852,1.721336e-02,0.999999,0.001309,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1988,0.376728,0.926324
1,107.23,48.8878,-118.2105,149,49.159047,-118.186462,0,2019,0.999852,1.721336e-02,0.999995,0.003200,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1978,-0.983709,0.179767
2,220.11,42.1808,-112.2620,4154,43.150704,-112.154481,0,2019,0.999852,1.721336e-02,0.999993,0.003709,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1962,0.946988,0.321270
3,45.00,46.2306,-112.1138,1939,47.034331,-112.561071,0,2019,0.999852,1.721336e-02,0.999985,0.005527,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1967,0.978740,0.205104
4,41.96,38.4207,-79.4629,99,38.674999,-78.632459,0,2019,0.999852,1.721336e-02,0.999909,0.013526,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1986,0.073095,0.997325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,43.77,40.4931,-91.8912,519,39.946837,-91.333331,0,2020,1.000000,-2.449294e-16,0.999993,-0.003854,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1966,0.726608,0.687053
1852390,111.84,29.0393,-95.4401,28739,29.661049,-96.186633,0,2020,1.000000,-2.449294e-16,0.999993,-0.003709,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1999,0.997630,-0.068802
1852391,86.88,46.1966,-118.9017,3684,46.658340,-119.715054,0,2020,1.000000,-2.449294e-16,0.999995,-0.003272,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1981,0.852078,-0.523416
1852392,7.99,44.6255,-116.4493,129,44.470525,-117.080888,0,2020,1.000000,-2.449294e-16,0.999997,-0.002618,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,1,0,1,0,1965,0.962309,-0.271958
1852393,38.13,35.6665,-97.4798,116001,36.210097,-97.036372,0,2020,1.000000,-2.449294e-16,0.999998,-0.001891,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1993,-0.618671,0.785650

## Normalize
Dont worry about text features but you must normalize the numeric features. 
* Provide rationale as to why the particular normalization feature was selected.

**We will use mean standardization.  This puts all values roughly on the scale of both the one-hot-encoded features as well as the sine/cosine facetized datetime features.**  
**Mean standardization is also outlier resilient.**

In [32]:
std_scaler = StandardScaler()
cols2std = ['amt', 'lat', 'long', 'city_pop', 'merch_lat', 'merch_long', 'year', 'dob_year']
df[cols2std] = std_scaler.fit_transform(df[cols2std])

**Now check the normalized dataframe.**

In [33]:
df

,amt,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,doy_x,doy_y,sod_x,sod_y,category_entertainment,category_food_dining,category_gas_transport,category_grocery_net,category_grocery_pos,category_health_fitness,category_home,category_kids_pets,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,sex_F,sex_M,zip_cor_0,zip_cor_1,city_cor_0,city_cor_1,state_cor_0,state_cor_1,job_cor_0,job_cor_1,dob_year,dob_doy_x,dob_doy_y
0,-0.408741,-0.485167,0.658263,-0.282429,-0.495080,0.594463,0,-1.001455,0.999852,1.721336e-02,0.999999,0.001309,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0.845898,0.376728,0.926324
1,0.233378,2.040531,-2.035415,-0.293527,2.080082,-2.031915,0,-1.001455,0.999852,1.721336e-02,0.999995,0.003200,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0.270874,-0.983709,0.179767
2,0.942184,0.718034,-1.602731,-0.280243,0.903268,-1.593535,0,-1.001455,0.999852,1.721336e-02,0.999993,0.003709,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,-0.649165,0.946988,0.321270
3,-0.157381,1.516580,-1.591951,-0.287590,1.663928,-1.623084,0,-1.001455,0.999852,1.721336e-02,0.999985,0.005527,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,-0.361653,0.978740,0.205104
4,-0.176470,-0.023388,0.783024,-0.293693,0.026642,0.842714,0,-1.001455,0.999852,1.721336e-02,0.999909,0.013526,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,1,0,1,0,0.730894,0.073095,0.997325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,-0.165105,0.385251,-0.120991,-0.292300,0.275748,-0.080336,0,0.998547,1.000000,-2.449294e-16,0.999993,-0.003854,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,-0.419155,0.726608,0.687053
1852390,0.262326,-1.873227,-0.379132,-0.198697,-1.738860,-0.433054,0,0.998547,1.000000,-2.449294e-16,0.999993,-0.003709,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1.478425,0.997630,-0.068802
1852391,0.105595,1.509876,-2.085692,-0.281802,1.590285,-2.143007,0,0.998547,1.000000,-2.449294e-16,0.999995,-0.003272,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0.443381,0.852078,-0.523416
1852392,-0.389777,1.200084,-1.907308,-0.293593,1.161773,-1.951567,0,0.998547,1.000000,-2.449294e-16,0.999997,-0.002618,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,1,0,1,0,1,0,-0.476658,0.962309,-0.271958
1852393,-0.200520,-0.566465,-0.527497,0.090741,-0.456142,-0.494810,0,0.998547,1.000000,-2.449294e-16,0.999998,-0.001891,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,1,0,1.133411,-0.618671,0.785650

## Feature and Label Selection
Down select from your data, the input features and label(s)

***street*, *trans_num*, *unix_time*, *cc_num*, *merchant*, *first*, and *last* were dropped during the *Clean Up* section, for reasons discussed in the *Analysis* section.**

## Split into 3 data sets for training, validation, and test (Explain your % for each)

**We will use %80 train, %10 validation, and %10 split.**  
**Although the dataset is very large, we will not use a smaller validation+test percentage because there are relatively few *is_fraud=1* data points.**  
**It is necessary to straify on *is_fraud*.**

In [34]:
Y = df['is_fraud'].to_numpy()
X = df.drop(columns=['is_fraud']).to_numpy()
X_train, X_test, Y_train, Y_test =\
        train_test_split(X, Y, test_size=0.10, stratify=Y)
X_train, X_val, Y_train, Y_val =\
        train_test_split(X_train, Y_train, test_size=1/9, stratify=Y_train)

print('train/val/test data set sizes:\n')
print('X: {} {} {}'.format(X_train.shape, X_val.shape, X_test.shape))
print('Y: {} {} {}'.format(Y_train.shape, Y_val.shape, Y_test.shape))

train/val/test data set sizes:

X: (1481914, 38) (185240, 38) (185240, 38)
Y: (1481914,) (185240,) (185240,)

## Summary
# Provide your thoughts on the quality, amount, trustworthiness, diffencencies, timeliness, and available documentation on the data you selected.  This can be written and/or code to demonstrate your conclusions.
* Determine if the data selected is suitable for a machine learning ingest.
* Note there are other prepossessing steps depending on the data such as graphics, free form text, and graphs and/or the type of model such as a time series model.  These topics are covered in the upcoming modules.

**There seem to be no erroneous inputs, so I don't see the data to be deficient.  Although there are many data points, the data is highly imbalanced (less than 1% are labeled "1").  Because this data was likely automatically generated with each transaction, as opposed to manually created, I believe the data to be both accurately and precisely collected.  The documentation on the download page is informative to me.**  
  
**The data is suitable for a machine learning project.  15 of the original 22 features were usable.  After either one-hot-encoding or sine/cosine facetization, followed by mean standardization, the data is ready for numerically sensitive models such as neural networks.**

# Quality Check
After your analysis provide details on the following qualities of your selected data.
* Overall Quality of the data
* Sufficient amount of the data
* Spareness of any data categories (eg. no young adults)
* Trustworthiness of the data (Is it true?)
* Timeliness of the data (is it recent?)  What might be the problem if it is not?
* Note difficenties
* Available document on the data types, how the data was collected, how it was verified?

Provide your answers here for the quality check...

**I will adress the topics that were not already covered in the previous answer:**  
  
**The overall quality seems good enough for any machine learning model, as previously described.**

**Feature sparsity shouldn't be a problem.  Categorical features were handled by one-hot-encoding based on grouping (values with a perfect correlation with fraud versus those with very weak correlation).  The supposed lack of young adults shouldn't matter since birth year is ordinal.**
  
**The data is somewhat recent.  It is recent enough to make it a meaningful machine learning study.  It is not recent enough to keep security analysts on the cutting edge of fraud techniques/tactics/procedures.**